[tox]
env_list = setup
skipsdist = True
requires = tox-conda

[testenv:setup]
description = Create Conda environment and setup dependencies
conda_env_name = suite2p
conda_channels =
    conda-forge
    defaults
allowlist_externals =
    /usr/bin/mkdir
    /usr/bin/install
commands_pre =
    git submodule update --init --recursive
commands =
    pip install -v ./suite2p ./multiday-suite2p-public ./vr2p-fork ./2ACDC_parse
    pip install ipykernel paramiko==3.5.1 colorcet "dask[dataframe]"
    mkdir -p {env:HOME}/.multiday-suite2p
    install -v -m 0755 bash/extract_session_job.sh {env:HOME}/.multiday-suite2p/
    mkdir -p {env:HOME}/.linear2ac
    install -v -m 0755 bash/placefield_job.sh {env:HOME}/.linear2ac/
