[tox]
env_list = setup
skipsdist = True

[testenv:setup]
description = Create Conda environment and setup dependencies
allowlist_externals =
    conda
    mkdir
    install
    pip
    git
commands_pre =
    git submodule update --init --recursive
commands =
    conda run -n suite2p pip install -v ./suite2p ./multiday-suite2p-public ./vr2p-fork ./2ACDC_parse ipykernel paramiko==3.5.1 colorcet "dask[dataframe]"
    mkdir -p {env:HOME}/.multiday-suite2p
    install -v -m 0755 bash/extract_session_job.sh {env:HOME}/.multiday-suite2p/
    mkdir -p {env:HOME}/.linear2ac
    install -v -m 0755 bash/placefield_job.sh {env:HOME}/.linear2ac/
