from pathlib import Path
from datetime import datetime

import polars as pl
from sollertia_shared_assets import SessionData as SessionData
from ataraxis_data_structures import TrackerStatus

from .jobs import write_project_jobs as write_project_jobs
from ..shared_assets import (
    SESSION_PIPELINES as SESSION_PIPELINES,
    ProcessingPipelines as ProcessingPipelines,
    natural_sort as natural_sort,
    resolve_session_tracker_path as resolve_session_tracker_path,
)

MANIFEST_JOB_NAME: str
MANIFEST_AXES: tuple[str, ...]
MANIFEST_SEMI_FIELDS: tuple[str, ...]
_PIPELINE_STATUS_COLUMNS: dict[ProcessingPipelines, str]
_PROJECT_MANIFEST_SCHEMA: dict[str, pl.datatypes.classes.DataTypeClass | pl.DataType]
_MANIFEST_ROW_COLUMNS: tuple[str, ...]
_MANIFEST_SUMMARY_COLUMNS: tuple[str, ...]

def project_manifest_path(project_directory: Path) -> Path: ...
def generate_project_manifest(project_directory: Path, *, display_progress: bool = False) -> None: ...

class ProjectManifest:
    _data: pl.DataFrame
    def __init__(self, manifest_file: Path) -> None: ...
    def __repr__(self) -> str: ...
    def print_data(self) -> None: ...
    def print_summary(self, animal: str | None = None) -> None: ...
    def print_notes(self, animal: str | None = None) -> None: ...
    @property
    def data(self) -> pl.DataFrame: ...
    @property
    def animals(self) -> tuple[str, ...]: ...
    def get_sessions(self, animal: str | None = None, *, exclude_incomplete: bool = True) -> tuple[str, ...]: ...
    def get_session_data(self, session: str) -> pl.DataFrame: ...
    def get_animal_for_session(self, session: str) -> str: ...
    def get_system_for_session(self, session: str) -> str: ...
    def summarize(self) -> dict[str, int | list[str] | dict[str, int] | dict[str, dict[str, int]]]: ...
    def _display_frame(self) -> pl.DataFrame: ...
    def _get_filtered_sessions(
        self, animal: str | None = None, *, exclude_incomplete: bool = True
    ) -> tuple[str, ...]: ...

def _build_session_row(
    session_data: SessionData, project_directory: Path
) -> tuple[dict[str, str | datetime | bool | int | None], list[dict[str, str | int | None]]]: ...
def _read_pipeline_state(
    pipeline: ProcessingPipelines, tracker_path: Path
) -> tuple[TrackerStatus, list[dict[str, str | int | None]]]: ...
def _assert_status_column_coverage() -> None: ...
