from typing import Any
from pathlib import Path

import polars as pl
from sollertia_shared_assets import SessionData as SessionData

from .jobs import write_project_jobs as write_project_jobs
from ..shared_assets import (
    SESSION_PIPELINES as SESSION_PIPELINES,
    ProcessingPipelines as ProcessingPipelines,
    summarize_tracker as summarize_tracker,
    derive_tracker_status as derive_tracker_status,
    resolve_session_tracker_path as resolve_session_tracker_path,
)

MANIFEST_JOB_NAME: str
PIPELINE_STATUS_COLUMNS: dict[ProcessingPipelines, str]
PROJECT_MANIFEST_SCHEMA: dict[str, pl.datatypes.classes.DataTypeClass | pl.DataType]
_COMPLETED_STATUS: str

def project_manifest_path(project_directory: Path) -> Path: ...
def generate_project_manifest(project_directory: Path, *, display_progress: bool = False) -> None: ...

class ProjectManifest:
    _data: pl.DataFrame
    def __init__(self, manifest_file: Path) -> None: ...
    def __repr__(self) -> str: ...
    def print_data(self) -> None: ...
    def print_summary(self, animal: int | None = None) -> None: ...
    def print_notes(self, animal: int | None = None) -> None: ...
    @property
    def data(self) -> pl.DataFrame: ...
    @property
    def animals(self) -> tuple[int, ...]: ...
    def get_sessions(self, animal: int | None = None, *, exclude_incomplete: bool = True) -> tuple[str, ...]: ...
    def get_session_data(self, session: str) -> pl.DataFrame: ...
    def get_animal_for_session(self, session: str) -> int: ...
    def get_system_for_session(self, session: str) -> str: ...
    def summarize(self) -> dict[str, Any]: ...
    def _display_frame(self) -> pl.DataFrame: ...
    def _get_filtered_sessions(
        self, animal: int | None = None, *, exclude_incomplete: bool = True
    ) -> tuple[str, ...]: ...

def _build_session_row(
    session_data: SessionData, project_directory: Path
) -> tuple[dict[str, Any], list[dict[str, Any]]]: ...
def _read_pipeline_state(pipeline: ProcessingPipelines, tracker_path: Path) -> tuple[str, list[dict[str, Any]]]: ...
def _assert_status_column_coverage() -> None: ...
