"""This module binds the run_s2p function to work with additional configuration tools, data layout, and specific runtime
parameters used in the Sun lab. Primarily, this module is designed to expose the CLI function used to run suite2p
processing in the lab."""

import json
from typing import Any
from pathlib import Path

import click
from sl_shared_assets import SessionData, SingleDayS2PConfiguration
from ataraxis_base_utilities import LogLevel, console

from .single_day import run_s2p, resolve_ops, post_process, process_plane, resolve_binaries


@click.command()
@click.option(
    "-p",
    "--path",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="The absolute path to the root session directory to be processed.",
)
def process_session(path: str) -> None:
    """Runs the full suite2p single-session processing pipeline on the Mesoscope-acquired data of the target session.

    This CLI is primarily intended for running suite2p single-session processing on local machines for testing purposes.
    For data stored on the BioHPC server, use the CLI exposes as part of the sl-forgery library to efficiently
    parallelize all processing steps. This CLI is explicitly designed to integrate with data structures and hierarchies
    used in the Sun lab and will likely not work in all other contexts.
    """
    # Converts to Path
    session_path = Path(path)

    # Loads session data layout
    session_data = SessionData.load(session_path=session_path, on_server=False)

    # Uses available session data to generate the ops and db
    ops = _resolve_ops(session_data)
    db = _resolve_db(session_data)

    # Resolves ops and db
    ops_path = resolve_ops(ops=ops, db=db)

    # Starts the processing pipeline.
    run_s2p(ops_path=ops_path)


@click.command()
@click.option(
    "-p",
    "--path",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="The absolute path to the root session directory for which to generate the binaries.",
)
def prepare_binaries(path: str) -> None:
    """Runs the first processing step of the suite2p single-session processing pipeline on the Mesoscope-acquired data
    of the target session.

    This CLI is intended to be used together with Sun lab compute server job submission API to execute parallel suite2p
    processing. Specifically, it generates the ops.npy file used by all processing steps (step 0) and converts raw
    .tiff frames into plane-specific binary files (step 1). This CLI is explicitly designed to integrate with data
    structures and hierarchies used in the Sun lab and will likely not use in all other contexts.
    """

    # Converts to Path
    session_path = Path(path)

    # Loads session data layout
    session_data = SessionData.load(session_path=session_path, on_server=False)

    # Uses available session data to generate the ops and db
    ops = _resolve_ops(session_data)
    db = _resolve_db(session_data)

    # Generates the output suite2p directory and saves the combined 'ops' dictionary (ops+db) as 'ops.npy' file.
    ops_path = resolve_ops(ops=ops, db=db)

    # If necessary, converts Mesoscope frames from .tiff to suite2p BinaryFile format.
    resolve_binaries(ops_path)


@click.command()
@click.option(
    "-p",
    "--path",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="The absolute path to the root session directory that contains the plane data to process.",
)
@click.option(
    "-i",
    "--index",
    type=int,
    required=True,
    help="The zero-based integer index of the plane to process, relative to the list of all available planes.",
)
def process_single_plane(path: str, index: int) -> None:
    """Runs the second processing step of the suite2p single-session processing pipeline on the Mesoscope-acquired data
    of the target session.

    This CLI is intended to be used together with Sun lab compute server job submission API to execute parallel suite2p
    processing. Specifically, it uses the binary files and ops.npy generated by the 'prepare_binaries' CLI command to
    run the suite2p single-session pipeline on the target plane. To achieve maximum runtime efficiency, this CLI can
    be called for multiple planes at the same time. This CLI is explicitly designed to integrate with data
    structures and hierarchies used in the Sun lab and will likely not use in all other contexts.
    """
    # Converts to Path
    session_path = Path(path)

    # Loads session data layout
    session_data = SessionData.load(session_path=session_path, on_server=False)

    # Computes the path to the 'main' ops.npy file:
    ops_path = session_data.processed_data.mesoscope_data_path.joinpath("suite2p", "ops.npy")

    # If the file does not exist, aborts with an error.
    if not ops_path.exists():
        message = (
            f"Unable to carry out single-session plane processing. This step requires the 'ops.npy' file to be present "
            f"inside the session's processed_data/mesoscope_data/suite2p directory, but the file does not exist. Make "
            f"sure 'prepare_binaries' CLI command is called for this session before running this command."
        )
        console.error(message=message, error=FileNotFoundError)

    # Processes the target plane.
    process_plane(plane_index=index, ops_path=ops_path)


@click.command()
@click.option(
    "-p",
    "--path",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="The absolute path to the root session directory to post-process.",
)
def post_process(path: str) -> None:
    """Runs the third (final) processing step of the suite2p single-session processing pipeline on the
    Mesoscope-acquired data of the target session.

    This CLI is intended to be used together with Sun lab compute server job submission API to execute parallel suite2p
    processing. Specifically, it combines the data from one or more processed planes into a 'combined' plane. This step
    is required to carry out multi-session processing. This CLI is explicitly designed to integrate with data
    structures and hierarchies used in the Sun lab and will likely not use in all other contexts.
    """

    # Converts to Path
    session_path = Path(path)

    # Loads session data layout
    session_data = SessionData.load(session_path=session_path, on_server=False)

    # Computes the path to the 'main' ops.npy file:
    ops_path = session_data.processed_data.mesoscope_data_path.joinpath("suite2p", "ops.npy")

    # If the file does not exist, aborts with an error.
    if not ops_path.exists():
        message = (
            f"Unable to carry out single-session post-processing. This step requires the 'ops.npy' file to be present "
            f"inside the session's processed_data/mesoscope_data/suite2p directory, but the file does not exist. Make "
            f"sure 'prepare_binaries' and 'process_plane' CLI commands are called for this session before running this "
            f"command."
        )
        console.error(message=message, error=FileNotFoundError)

    # Carries out post-processing. Primarily, this involves generating the 'combined' plane required for the
    # multi-session pipeline.
    post_process(ops_path)


def _resolve_db(session_data: SessionData) -> dict[str, Any]:
    """Uses the data stored inside the mesoscope_data folder of the processed session to generate the 'db' suite2p
    dictionary.

    This worker function is used to manually build the 'db' dictionary, which is provided to the 'run_s2p' function call
    as an argument. To generate the 'db', this function first discovers and loads the ops.json file that should be
    stored inside the mesoscope_data folder, using it to make the initial 'db' instance. It then discovers the absolute
    paths to all .tiff and .tif files inside the folder and writes them to the 'db' as 'tiff_list' field. Finally, it
    also resolves the output and working suite2p directories using the data stored inside the input SessionData
    instance.

    Notes:
        The fields in the 'db' dictionary are identical to the fields inside the 'ops' dictionary, but 'db' values
        always take precedence (override) the 'ops' values.

    Args:
        session_data: The SessionData class instance initialized from the session_data.yaml file stored inside the
            processed session's raw_data folder.

    Returns:
        A dictionary to be passed as the 'db' argument to the 'run_s2p' function call.
    """

    # First, loads ops.json as the initial 'db' dictionary
    ops_path = Path(session_data.raw_data.mesoscope_data_path).joinpath("ops.json")
    with open(ops_path, "r") as f:
        precursor: dict[str, Any] = json.load(f)

    # Depending on the 'version' of the ops.json file, it may be missing some expected information or, alternatively,
    # contain extra data. Therefore, instead of just using the precursor as 'db', we manually use it to generate the
    # 'db' with the necessary data.
    db = {}

    # 'nchannels' has been added in sl-experiment 2.0,0, so many target ops files will not have it. Defaults to
    # nchannels == 1, as this is true for Tyche data and early Sun lab data.
    # noinspection PyArgumentList
    precursor.setdefault("nchannels", 1)

    # Generates the db by pulling fields from the precursor. All fields used below are expected to be present in all
    # precursor file versions.
    db.update(
        {
            "fs": precursor["fs"],
            "nplanes": precursor["nplanes"],
            "nchannels": precursor["nchannels"],
            "nrois": precursor["nrois"],
            "mesoscan": precursor["mesoscan"],
            "dx": precursor["dx"],
            "dy": precursor["dy"],
            "lines": precursor["lines"],
        }
    )

    # Discovers the paths to all TIFF stacks inside the folder. Since our preprocessing pipeline uses '.tiff' extension
    # and suite2p expects '.tif' extensions, we have to build the list manually.
    tiff_files = list(session_data.raw_data.mesoscope_data_path.glob("*.tif"))
    tiff_files.extend(session_data.raw_data.mesoscope_data_path.glob("*.tiff"))
    db["tiff_list"] = [str(file) for file in tiff_files]

    # Finally, resolves the paths used during session processing using the SessionData class. Specifically, sets the
    # input and output folders to the raw_data and the processed_data paths, respectively.
    db.update(
        {
            "data_path": [session_data.raw_data.mesoscope_data_path],  # Source mesoscope_data folder
            "save_path0": str(session_data.processed_data.mesoscope_data_path),  # Destination mesoscope_data folder
            "save_folder": [],  # Forces the pipeline to use the default 'suite2p' output folder in all cases
        }
    )

    # Returns the generated 'db' dictionary to caller
    return db


def _resolve_ops(session_data: SessionData) -> dict[str, Any]:
    """Uses the data stored inside the suite2p_configuration.yaml file of the processed session's project to generate
    the 'ops' suite2p dictionary.

    This worker function is used to load the majority of suite2p configuration data, which is typically shared between
    all sessions of a given project. It is expected that the configuration file is stored under the 'configuration'
    folder of the project 'processed data' directory hierarchy.

    Notes:
        If the configuration file does not exist, the function generates the configuration class instance using default
        parameters. While this allows running the suite2p processing, it is highly encouraged to manually generate the
        configuration file to achieve the best processing results, fine-tuned for each project.

        The 'ops' dictionary generated by this function is partially overwritten by the 'db' dictionary, which specifies
        session-specific override parameters for each processing runtime.

    Args:
        session_data: The SessionData class instance initialized from the session_data.yaml file stored inside the
            processed session's raw_data folder.

    Returns:
        A dictionary to be passed as the 'ops' argument to the 'run_s2p' function call.
    """

    # Resolves the path to the project's S2P configuration file. It is expected that any well-configured project
    # stores a configuration .yaml file at the specified path.
    config_path = session_data.configuration_data.single_day_s2p_configuration_path
    # Although we expect the config to be present, in the case it is not, we generate and use the 'default'
    # configuration parameters. Note; these parameters are modeled after the Tyche project used in OSM manuscript, so
    # this may not work for the modern GCaMP8 animals.
    if not config_path.exists():
        config = SingleDayS2PConfiguration()
        warning = (
            f"No suite2p configuration file found at {config_path}. Generating a local configuration instance with "
            f"default processing parameters. Note, it is highly recommended to provide a configuration file that has "
            f"been optimized for working with the data generated by the project."
        )
        console.echo(message=warning, level=LogLevel.WARNING)
    else:
        # If the config .yaml file exists at the specified path, loads class data from the .yaml file.
        config = SingleDayS2PConfiguration.from_yaml(file_path=config_path)  # type: ignore

    # Translates config data to 'ops' dictionary and returns it to caller.
    return config.to_ops()
