"""Provides assets for assembling two-photon fluorescence datasets from cindra single-recording and multi-recording
processing pipeline outputs.
"""

from __future__ import annotations

from enum import StrEnum
from typing import TYPE_CHECKING

import numpy as np
import polars as pl
from ataraxis_base_utilities import console
from sollertia_shared_assets import MesoscopeDirectories

from .metadata import BehaviorDataFiles

if TYPE_CHECKING:
    from pathlib import Path

    from numpy.typing import NDArray


_MILLISECONDS_PER_SECOND: int = 1000
"""The number of milliseconds in one second."""

_MICROSECONDS_PER_MILLISECOND: int = 1000
"""The number of microseconds in one millisecond."""

_MICROSECONDS_PER_SECOND: int = 1_000_000
"""The number of microseconds in one second."""

_MICROSECONDS_PER_MINUTE: int = 60 * 1_000_000
"""The number of microseconds in one minute."""

_SCAN_PULSE_TOLERANCE_MS: int = 20
"""The tolerance, in milliseconds, applied around the expected scan pulse duration when filtering logged pulses."""

_FRAME_VARIANT_METADATA_FILENAME: str = "frame_variant_metadata.npz"
"""The filename of the ScanImage per-frame metadata archive written into each session's raw mesoscope_data
directory by the sollertia-experiment preprocessing pipeline. Stores one entry per acquired TIFF frame and is
used by the ScanImage-based fallback alignment path."""

_SI_FRAME_NUMBER_KEY: str = "frameNumberAcquisition"
"""The key name of the strictly monotonic per-frame counter inside the ScanImage frame_variant_metadata archive.
The archive is stored in TIFF-page concatenation order, which can interleave frames across stack files, so this
counter is used to recover the chronological frame ordering before timestamps are read."""

_SI_FRAME_TIMESTAMP_KEY: str = "frameTimestamps_sec"
"""The key name of the per-frame ScanImage clock timestamps (seconds) inside the frame_variant_metadata archive."""

_SI_MATCH_TOLERANCE_US: int = 50_000
"""The tolerance, in microseconds, applied when matching microcontroller-logged TTL pulse rising edges to
ScanImage-recorded frame timestamps in the fallback alignment path. Set generously to absorb both pulse-edge
jitter and the small clock drift between ScanImage and the microcontroller, observed in production data up to
~15 ms over a one-hour session."""

_SI_ANCHOR_SEARCH_LIMIT: int = 10
"""The maximum number of leading TTL pulses considered as candidate anchors when estimating the clock offset
between ScanImage and the microcontroller in the fallback alignment path. Front-of-session noise is typically
two short pulses, so the default leaves headroom for unusual setups."""


class FluorescenceColumn(StrEnum):
    """Defines the neuropil-subtracted, baseline-corrected fluorescence columns produced by the forging pipeline that
    are valid analysis inputs for the place-cell, reward-cell, and SCE detectors.
    """

    SINGLE_DAY_SUBTRACTED = "single_day_subtracted_fluorescence"
    """Single-recording neuropil-subtracted, baseline-corrected dF/F0 fluorescence."""
    MULTI_DAY_SUBTRACTED = "multi_day_subtracted_fluorescence"
    """Multi-recording neuropil-subtracted, baseline-corrected dF/F0 fluorescence aligned across recording days."""


def assemble_cindra_dataset(
    cindra_data_path: Path,
    behavior_data_path: Path,
    multiday_data_path: Path,
    raw_data_path: Path,
) -> pl.DataFrame:
    """Assembles the target session's two-photon fluorescence dataset from the data generated by Cindra's
    single-recording and multi-recording processing pipelines.

    Args:
        cindra_data_path: The path to the single-recording cindra output directory containing the combined
            (multi-plane merged) fluorescence traces, cell classification, and metadata files.
        behavior_data_path: The path to the behavior data directory containing the mesoscope frame TTL timestamps.
        multiday_data_path: The path to the session's multi-recording cindra output directory (the directory that
            directly contains ``cell_fluorescence.npy`` and its companions).
        raw_data_path: The path to the session's raw_data directory. Used by the ScanImage-based fallback alignment
            path to load the per-frame metadata archive when the duration-tolerance filter alone cannot recover the
            expected frame count.

    Returns:
        The Polars DataFrame that contains the assembled single-recording and multi-recording cell fluorescence data.
    """
    # Queries the number of frames processed by cindra via a memory-mapped header read. This handles rare cases where
    # the log has more frame stamps than recorded frames (typically when the user manually triggers mesoscope scanning
    # outside the expected time slot): if the log has more frames than the cindra data, the log is clipped at the
    # front, since aberrant frames must come from a period before the main experiment runtime.
    _, frames = np.load(file=cindra_data_path.joinpath("cell_fluorescence.npy"), mmap_mode="r").shape

    # Loads the combined cindra metadata archive and extracts the per-plane sampling rate in Hz. NPZ archives do not
    # support memory mapping, so the context manager is used to keep the archive open only long enough to pull the
    # scalar out. The scanning rate is used to derive the expected scan pulse duration window in milliseconds for
    # filtering logged scan pulses.
    with np.load(file=cindra_data_path.joinpath("combined_metadata.npz")) as metadata:
        scanning_frequency = float(metadata["sampling_rate"][0])
    expected_duration_ms = _MILLISECONDS_PER_SECOND / scanning_frequency
    min_duration = expected_duration_ms - _SCAN_PULSE_TOLERANCE_MS
    max_duration = expected_duration_ms + _SCAN_PULSE_TOLERANCE_MS

    # Loads the mesoscope frame acquisition timestamps collected by the microcontroller logging system during the
    # session's data acquisition.
    mesoscope_frame_data = pl.read_ipc(
        source=behavior_data_path.joinpath(BehaviorDataFiles.MESOSCOPE_FRAME), memory_map=True
    )

    # Sorts by time to ensure the correct order and computes TTL state transitions once.
    mesoscope_frame_data = mesoscope_frame_data.sort("time_us")
    ttl_diff = pl.col("ttl_state").diff().fill_null(value=0)
    mesoscope_frame_data = mesoscope_frame_data.with_columns(
        ttl_diff.alias("ttl_diff"),
        (ttl_diff == 1).cum_sum().alias("pulse_id"),
    )

    # Extracts one row per pulse via separate rising-edge (pulse start) and falling-edge (pulse end) filters, then
    # joins by pulse ID. This avoids intermediate boolean columns and per-row window evaluation (forward_fill /
    # backward_fill over groups). Pulses missing either edge are excluded by the inner join, matching the prior
    # is_not_null filter on pulse duration.
    rising_edges = mesoscope_frame_data.filter(pl.col("ttl_diff") == 1).select(
        "pulse_id", pl.col("time_us").alias("pulse_start")
    )
    falling_edges = mesoscope_frame_data.filter(pl.col("ttl_diff") == -1).select(
        "pulse_id", pl.col("time_us").alias("pulse_end")
    )

    # Builds the chronologically-ordered table of paired pulses with a duration column. The unfiltered table is
    # retained because the ScanImage-based fallback alignment path consumes it whenever the duration-tolerance
    # filter alone cannot recover the expected frame count.
    paired_pulses: pl.DataFrame = (
        rising_edges.join(falling_edges, on="pulse_id", how="inner")
        .with_columns(
            ((pl.col("pulse_end") - pl.col("pulse_start")) / _MICROSECONDS_PER_MILLISECOND).alias("duration_ms")
        )
        .sort("pulse_start")
    )

    # Primary alignment path: keeps only those pulses whose duration falls within the expected scan-pulse window.
    frame_aligned_data: pl.DataFrame = (
        paired_pulses.filter(pl.col("duration_ms").is_between(min_duration, max_duration))
        .select(
            pl.col("pulse_id").alias("frame"),
            pl.col("pulse_start").alias("time_us"),
        )
        .sort("frame")
    )

    # When the log has more in-window pulses than the cindra fluorescence frame count, the front of the log is
    # clipped because aberrant frames must come from a period before the main experiment runtime. When the log has
    # fewer in-window pulses than the cindra frame count, the duration filter has rejected real frames whose TTL
    # signal briefly fell outside the tolerance window — the ScanImage-based fallback recovers them by matching
    # each logged TTL rising edge to its nearest ScanImage-recorded frame timestamp.
    if len(frame_aligned_data) > frames:
        frame_aligned_data = frame_aligned_data.tail(frames)
    elif len(frame_aligned_data) < frames:
        frame_aligned_data = _align_pulses_to_scanimage(
            paired_pulses=paired_pulses,
            raw_data_path=raw_data_path,
            expected_frame_count=frames,
        )

    # Re-assigns frame IDs starting from 1 as unsigned 32-bit integers and adds a column that reflects the
    # within-session time as the number of minutes elapsed since session onset (stored as fp32).
    frame_aligned_data = frame_aligned_data.with_columns(
        pl.int_range(1, len(frame_aligned_data) + 1, dtype=pl.UInt32).alias("frame"),
        ((pl.col("time_us") - pl.col("time_us").min()) / _MICROSECONDS_PER_MINUTE)
        .round(2)
        .cast(pl.Float32)
        .alias("elapsed_minutes"),
    )

    # Uses the single-recording cell classification data to create a filtering mask that excludes non-cell ROIs from
    # the analysis dataset. cindra stores classification results as a (num_rois, 2) float32 array where column 0 holds
    # the is_cell label (1.0 or 0.0) and column 1 holds the classifier probability.
    classification = np.load(file=cindra_data_path.joinpath("cell_classification.npy"), mmap_mode="r")
    is_cell_mask: NDArray[np.bool_] = classification[:, 0] == 1

    # Streams fluorescence Series into the DataFrame one file at a time to keep peak memory at one
    # array-worth instead of eight.
    fluorescence_sources: tuple[tuple[Path, str, str, NDArray[np.bool_] | None], ...] = (
        (cindra_data_path, "cell_fluorescence.npy", "single_day_cell_fluorescence", is_cell_mask),
        (cindra_data_path, "neuropil_fluorescence.npy", "single_day_neuropil_fluorescence", is_cell_mask),
        (cindra_data_path, "subtracted_fluorescence.npy", FluorescenceColumn.SINGLE_DAY_SUBTRACTED.value, is_cell_mask),
        (cindra_data_path, "spikes.npy", "single_day_spikes", is_cell_mask),
        (multiday_data_path, "cell_fluorescence.npy", "multi_day_cell_fluorescence", None),
        (multiday_data_path, "neuropil_fluorescence.npy", "multi_day_neuropil_fluorescence", None),
        (multiday_data_path, "subtracted_fluorescence.npy", FluorescenceColumn.MULTI_DAY_SUBTRACTED.value, None),
        (multiday_data_path, "spikes.npy", "multi_day_spikes", None),
    )
    for source_path, filename, column_name, mask in fluorescence_sources:
        series = _load_cindra_fluorescence(
            data_path=source_path, filename=filename, column_name=column_name, cell_mask=mask
        )
        frame_aligned_data = frame_aligned_data.with_columns(series)
        del series

    return frame_aligned_data


def _load_cindra_fluorescence(
    data_path: Path,
    filename: str,
    column_name: str,
    *,
    cell_mask: NDArray[np.bool_] | None = None,
) -> pl.Series:
    """Loads fluorescence data from a cindra .npy file and returns it as a Polars Array-typed Series.

    Args:
        data_path: The path to the directory that stores the fluorescence data to be loaded.
        filename: The name of the .npy file that stores the data to be loaded.
        column_name: The name to assign to the returned Series.
        cell_mask: The optional boolean mask to filter out non-cell ROIs. Must match the ROI axis of the loaded
            fluorescence array.

    Returns:
        A Polars Array-typed Series containing the fluorescence data with shape (frames, rois).
    """
    # Memory-maps the cindra fluorescence array to defer reading the pixel data until the selection is applied.
    fluorescence = np.load(file=data_path.joinpath(filename), mmap_mode="r")

    # Drops the masked intermediate before returning to keep peak memory at one array-worth instead of two.
    if cell_mask is not None:
        masked = fluorescence[cell_mask, :]
        transposed = np.ascontiguousarray(masked.T, dtype=np.float32)
        del masked
    else:
        transposed = np.ascontiguousarray(fluorescence.T, dtype=np.float32)

    return pl.Series(name=column_name, values=transposed)


def _align_pulses_to_scanimage(
    paired_pulses: pl.DataFrame, raw_data_path: Path, expected_frame_count: int
) -> pl.DataFrame:
    """Aligns microcontroller-logged TTL pulses to ScanImage-acquired frames using ScanImage's per-frame metadata
    archive. This is the fallback path used when the duration-tolerance filter on TTL pulses produces fewer rows
    than the cindra fluorescence frame count.

    The mesoscope hardware can briefly hold a TTL signal outside the expected pulse-duration window even when the
    corresponding scan was acquired (typically when one frame's TTL is delayed and clips the next frame's TTL
    onset). ScanImage writes one entry per acquired TIFF to ``frame_variant_metadata.npz``, so its per-frame
    timestamps are the authoritative record of which TTL rising edges correspond to real frames. Pulses that do
    not match any ScanImage frame within the configured tolerance window are dropped as electrical noise, which
    is typically clustered at the session's start (mesoscope arming glitches) and end (extra emissions after
    ScanImage stopped acquiring).

    Args:
        paired_pulses: The DataFrame of unfiltered paired rising/falling TTL edges with the columns ``pulse_id``,
            ``pulse_start``, ``pulse_end``, and ``duration_ms``, sorted by ``pulse_start``.
        raw_data_path: The path to the session's raw_data directory. The ScanImage metadata archive is resolved
            as ``raw_data_path / mesoscope_data / frame_variant_metadata.npz``.
        expected_frame_count: The number of frames recorded by cindra; used as the authoritative target count for
            the alignment.

    Returns:
        A Polars DataFrame with the columns ``frame`` (the original pulse_id of each matched real frame) and
        ``time_us`` (the rising-edge timestamp in microseconds), sorted by ``frame`` and containing exactly
        ``expected_frame_count`` rows.

    Raises:
        ValueError: If the ScanImage metadata archive is missing, if its frame count does not match the cindra
            frame count, or if the produced alignment does not contain exactly ``expected_frame_count`` rows.
    """
    metadata_path = raw_data_path.joinpath(MesoscopeDirectories.MESOSCOPE_DATA, _FRAME_VARIANT_METADATA_FILENAME)
    if not metadata_path.is_file():
        message = (
            f"Unable to apply the ScanImage-based fallback alignment for the cindra dataset assembly. The "
            f"expected per-frame metadata archive '{metadata_path}' does not exist."
        )
        console.error(message=message, error=ValueError)

    # ScanImage writes its per-frame metadata in TIFF-page-concatenation order, which interleaves frames across
    # stack files. Sorting by the strictly monotonic frame counter restores chronological order before the
    # timestamps can be matched against TTL rising edges. NPZ archives do not support memory mapping, so the
    # context manager is used to keep the archive open only long enough to copy the two arrays.
    with np.load(file=metadata_path) as metadata:
        frame_numbers = np.asarray(metadata[_SI_FRAME_NUMBER_KEY])
        frame_seconds = np.asarray(metadata[_SI_FRAME_TIMESTAMP_KEY])
    chronological_order = np.argsort(frame_numbers, kind="stable")
    si_microseconds = (frame_seconds[chronological_order] * _MICROSECONDS_PER_SECOND).astype(np.int64)

    # The ScanImage archive must contain exactly as many entries as cindra's frame count; if it does not, the
    # input data is internally inconsistent and alignment cannot proceed.
    if si_microseconds.size != expected_frame_count:
        message = (
            f"Unable to apply the ScanImage-based fallback alignment for the cindra dataset assembly. The cindra "
            f"processing pipeline reported {expected_frame_count} frames, but the ScanImage metadata archive "
            f"'{metadata_path}' contains {si_microseconds.size} entries."
        )
        console.error(message=message, error=ValueError)

    pulse_microseconds = paired_pulses["pulse_start"].to_numpy().astype(np.int64)
    pulse_ids = paired_pulses["pulse_id"].to_numpy()

    # Estimates the constant clock offset between ScanImage and the microcontroller log by anchoring a candidate
    # TTL pulse to the first ScanImage frame. The first few TTL pulses may be electrical glitches captured during
    # mesoscope arming, so the search ranges over the first few plausible anchors and selects the offset that
    # yields the most pulse-to-frame matches within the tolerance window.
    best_match_count = -1
    best_offset = 0
    anchor_count = min(_SI_ANCHOR_SEARCH_LIMIT, pulse_microseconds.size)
    for anchor_index in range(anchor_count):
        candidate_offset = int(pulse_microseconds[anchor_index]) - int(si_microseconds[0])
        match_count = _count_matches_within_tolerance(
            pulse_microseconds=pulse_microseconds,
            si_microseconds=si_microseconds + candidate_offset,
        )
        if match_count > best_match_count:
            best_match_count = match_count
            best_offset = candidate_offset

    aligned_si_microseconds = si_microseconds + best_offset

    # Each TTL pulse is matched to the nearest aligned ScanImage frame. Conflicts where multiple pulses claim the
    # same frame are resolved by keeping the pulse closer to the frame's expected time. Pulses outside the
    # tolerance window are treated as noise and dropped.
    nearest_si_index = _nearest_target_index(values=pulse_microseconds, sorted_targets=aligned_si_microseconds)
    nearest_distance = np.abs(pulse_microseconds - aligned_si_microseconds[nearest_si_index])
    within_tolerance = nearest_distance < _SI_MATCH_TOLERANCE_US

    keep_pulse = np.zeros(pulse_microseconds.size, dtype=np.bool_)
    closest_pulse_per_frame: dict[int, tuple[int, int]] = {}
    for pulse_index in np.flatnonzero(within_tolerance):
        si_index = int(nearest_si_index[pulse_index])
        distance = int(nearest_distance[pulse_index])
        existing = closest_pulse_per_frame.get(si_index)
        if existing is not None and existing[0] <= distance:
            continue
        if existing is not None:
            keep_pulse[existing[1]] = False
        closest_pulse_per_frame[si_index] = (distance, int(pulse_index))
        keep_pulse[pulse_index] = True

    if int(keep_pulse.sum()) != expected_frame_count:
        message = (
            f"Unable to apply the ScanImage-based fallback alignment for the cindra dataset assembly. The "
            f"matching produced {int(keep_pulse.sum())} pulses, but cindra reports {expected_frame_count} "
            f"frames. The TTL log and ScanImage metadata cannot be reconciled within the configured "
            f"±{_SI_MATCH_TOLERANCE_US // _MICROSECONDS_PER_MILLISECOND} ms tolerance window."
        )
        console.error(message=message, error=ValueError)

    keep_indices = np.flatnonzero(keep_pulse)
    return pl.DataFrame(
        {
            "frame": pulse_ids[keep_indices],
            "time_us": pulse_microseconds[keep_indices],
        }
    ).sort("frame")


def _count_matches_within_tolerance(pulse_microseconds: NDArray[np.int64], si_microseconds: NDArray[np.int64]) -> int:
    """Counts how many TTL pulse rising edges have a ScanImage frame within ``_SI_MATCH_TOLERANCE_US``.

    Args:
        pulse_microseconds: The microcontroller-logged TTL pulse rising-edge timestamps in microseconds.
        si_microseconds: The ScanImage per-frame timestamps in microseconds, sorted in ascending order and shifted
            into the microcontroller's clock frame by the candidate offset.

    Returns:
        The number of pulses whose nearest ScanImage frame is within the tolerance window.
    """
    nearest_index = _nearest_target_index(values=pulse_microseconds, sorted_targets=si_microseconds)
    nearest_distance = np.abs(pulse_microseconds - si_microseconds[nearest_index])
    return int((nearest_distance < _SI_MATCH_TOLERANCE_US).sum())


def _nearest_target_index(values: NDArray[np.int64], sorted_targets: NDArray[np.int64]) -> NDArray[np.intp]:
    """Returns the index, into ``sorted_targets``, of the nearest target for each query value.

    Args:
        values: The query values.
        sorted_targets: The candidate targets, sorted in strictly ascending order. Must contain at least two
            elements.

    Returns:
        The index, into ``sorted_targets``, of the nearest target for each query value.
    """
    upper = np.clip(np.searchsorted(sorted_targets, values), 1, sorted_targets.size - 1)
    left_distance = np.abs(values - sorted_targets[upper - 1])
    right_distance = np.abs(values - sorted_targets[upper])
    return np.where(left_distance < right_distance, upper - 1, upper)
