from enum import StrEnum

class BehaviorDataFiles(StrEnum):
    ENCODER = "encoder_data.feather"
    VALVE = "valve_data.feather"
    GAS_PUFF = "gas_puff_data.feather"
    LICK = "lick_data.feather"
    BRAKE = "brake_data.feather"
    TORQUE = "torque_data.feather"
    SCREEN = "screen_data.feather"
    MESOSCOPE_FRAME = "mesoscope_frame_data.feather"
    SYSTEM_STATE = "system_state_data.feather"
    RUNTIME_STATE = "runtime_state_data.feather"
    REINFORCING_GUIDANCE = "reinforcing_guidance_state_data.feather"
    AVERSIVE_GUIDANCE = "aversive_guidance_state_data.feather"
    VR_CUE = "vr_cue_data.feather"
    VR_TRIGGER_ZONE = "vr_trigger_zone_data.feather"
    TRIAL = "trial_data.feather"

class VideoDataFiles(StrEnum):
    FACE_CAMERA_TIMESTAMPS = "face_camera_timestamps.feather"
    FACE_CAMERA_ENERGY = "face_camera_energy.feather"
    FACE_CAMERA_PUPIL = "face_camera_pupil.feather"
    BODY_CAMERA_TIMESTAMPS = "body_camera_timestamps.feather"
    BODY_CAMERA_ENERGY = "body_camera_energy.feather"

class DatasetColumn(StrEnum):
    TIME_US = "time_us"
    ELAPSED_MINUTES = "elapsed_minutes"
    BRAKE = "brake"
    SCREENS = "screens"
    TORQUE_N_CM = "torque_N_cm"
    DISTANCE_CM = "distance_cm"
    SPEED_CM_S = "speed_cm_s"
    LICK = "lick"
    WATER_UL = "water_uL"
    REWARD = "reward"
    SYSTEM_STATE = "system_state"
    TRIAL = "trial"
    TRIAL_TYPE = "trial_type"
    CUE = "cue"
    IN_TRIGGER_ZONE = "in_trigger_zone"
    RUNTIME_STATE = "runtime_state"
    REINFORCING_GUIDED = "reinforcing_guided"
    AVERSIVE_GUIDED = "aversive_guided"
    FRAME = "frame"
    SINGLE_DAY_CELL_FLUORESCENCE = "single_day_cell_fluorescence"
    SINGLE_DAY_NEUROPIL_FLUORESCENCE = "single_day_neuropil_fluorescence"
    SINGLE_DAY_SUBTRACTED_FLUORESCENCE = "single_day_subtracted_fluorescence"
    SINGLE_DAY_SPIKES = "single_day_spikes"
    MULTI_DAY_CELL_FLUORESCENCE = "multi_day_cell_fluorescence"
    MULTI_DAY_NEUROPIL_FLUORESCENCE = "multi_day_neuropil_fluorescence"
    MULTI_DAY_SUBTRACTED_FLUORESCENCE = "multi_day_subtracted_fluorescence"
    MULTI_DAY_SPIKES = "multi_day_spikes"
    FACE_CAMERA_MOTION_ENERGY = "face_camera_motion_energy"
    FACE_CAMERA_FRAME_LUMINANCE = "face_camera_frame_luminance"
    BODY_CAMERA_MOTION_ENERGY = "body_camera_motion_energy"
    BODY_CAMERA_FRAME_LUMINANCE = "body_camera_frame_luminance"
    PUPIL_CENTER_X_PX = "pupil_center_x_px"
    PUPIL_CENTER_Y_PX = "pupil_center_y_px"
    PUPIL_DIAMETER_PX = "pupil_diameter_px"
    PUPIL_AREA_PX2 = "pupil_area_px2"
    PUPIL_FIT_CONDITION = "pupil_fit_condition"
    PUPIL_FIT_RESIDUAL_PX = "pupil_fit_residual_px"
    EYE_CENTER_X_PX = "eye_center_x_px"
    EYE_CENTER_Y_PX = "eye_center_y_px"
    EYE_WIDTH_PX = "eye_width_px"
    EYE_HEIGHT_PX = "eye_height_px"
    EYE_OPENNESS = "eye_openness"
    BLINKING_STATE = "blinking_state"
    DILATION_STATE = "dilation_state"
    REFLECTION_X_PX = "reflection_x_px"
    REFLECTION_Y_PX = "reflection_y_px"
    PUPIL_REFLECTION_OFFSET_X_PX = "pupil_reflection_offset_x_px"
    PUPIL_REFLECTION_OFFSET_Y_PX = "pupil_reflection_offset_y_px"
    PUPIL_IN_EYE_X = "pupil_in_eye_x"
    PUPIL_IN_EYE_Y = "pupil_in_eye_y"

_COLUMN_DESCRIPTIONS: dict[DatasetColumn, str]
MESOSCOPE_COLUMN_DESCRIPTIONS: dict[str, str]
