"""Provides assets for assembling two-photon fluorescence datasets from cindra single-recording and multi-recording
processing pipeline outputs.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import polars as pl

if TYPE_CHECKING:
    from pathlib import Path

    from numpy.typing import NDArray


def _add_cindra_fluorescence_column(
    df: pl.DataFrame,
    data_path: Path,
    filename: str,
    column_name: str,
    *,
    cell_mask: NDArray[np.bool_] | None = None,
) -> pl.DataFrame:
    """Updates the input dataframe to include a column storing the fluorescence data loaded from the specified
    cindra .npy file.

    Args:
        df: The Polars dataframe to be updated with the loaded fluorescence data.
        data_path: The path to the directory that stores the fluorescence data to be loaded.
        filename: The name of the .npy file that stores the data to be loaded.
        column_name: The name of the column under which to store the extracted data in the modified dataframe.
        cell_mask: The optional boolean mask to filter out non-cell ROIs. Must match the ROI axis of the loaded
            fluorescence array.

    Returns:
        The dataframe that includes the loaded fluorescence data stored as an Array datatype under the specified column
        name.
    """
    # Memory-maps the cindra fluorescence array to defer reading the pixel data until the selection is applied.
    fluorescence = np.load(data_path.joinpath(filename), mmap_mode="r")

    # Applies the cell mask if provided.
    if cell_mask is not None:
        fluorescence = fluorescence[cell_mask, :]

    # Gets ROI count for Array field width.
    roi_count = fluorescence.shape[0]

    # Transposes (ROI, Frame) to (Frame, ROI) and converts to a list of per-frame arrays (required to build a Polars
    # Array column). cindra already stores traces as float32, so no additional cast is needed.
    fluorescence_lists = [row.tolist() for row in np.ascontiguousarray(fluorescence.T)]

    return df.with_columns(
        [
            pl.Series(
                name=column_name,
                values=fluorescence_lists,
                dtype=pl.List(pl.Float32),
            ).list.to_array(width=roi_count)
        ]
    )


def assemble_cindra_dataset(session_data_path: Path, multiday_data_path: Path) -> pl.DataFrame:
    """Assembles the target session's two-photon fluorescence dataset from the data generated by Cindra's
    single-recording and multi-recording processing pipelines.

    Args:
        session_data_path: The path to the session's processed data directory.
        multiday_data_path: The path to the session's multi-recording cindra output directory (the directory that
            directly contains ``cell_fluorescence.npy`` and its companions).

    Returns:
        The Polars DataFrame that contains the assembled single-recording and multi-recording cell fluorescence data.
    """
    # Resolves the path to the single-recording cindra output directory. Combined (multi-plane merged) traces and
    # metadata now live at the cindra root rather than in a dedicated 'combined' subdirectory.
    single_day_data = session_data_path.joinpath("processed_data", "mesoscope_data", "cindra")

    # Resolves the path to the behavior data directory.
    behavior_data = session_data_path.joinpath("processed_data", "behavior_data")

    # Queries the number of frames processed by cindra via a memory-mapped header read. This handles rare cases where
    # the log has more frame stamps than recorded frames (typically when the user manually triggers mesoscope scanning
    # outside the expected time slot): if the log has more frames than the cindra data, the log is clipped at the
    # front, since aberrant frames must come from a period before the main experiment runtime.
    _, frames = np.load(single_day_data.joinpath("cell_fluorescence.npy"), mmap_mode="r").shape

    # Loads the combined cindra metadata archive and extracts the per-plane sampling rate in Hz. NPZ archives do not
    # support memory mapping, so the context manager is used to keep the archive open only long enough to pull the
    # scalar out. The scanning rate is used to derive the expected scan pulse duration window in milliseconds for
    # filtering logged scan pulses.
    with np.load(single_day_data.joinpath("combined_metadata.npz")) as metadata:
        scanning_frequency = float(metadata["sampling_rate"][0])
    min_duration = 1000 / scanning_frequency - 20
    max_duration = 1000 / scanning_frequency + 20

    # Loads the mesoscope frame acquisition timestamps collected by the microcontroller logging system during session's
    # data acquisition.
    mesoscope_frame_data = pl.read_ipc(
        behavior_data.joinpath("mesoscope_frame_data.feather"), memory_map=True, rechunk=True
    )

    # Sorts by time to ensure the correct order
    mesoscope_frame_data = mesoscope_frame_data.sort("time_us")

    # Creates pulse groups and find edges in one pass.
    mesoscope_frame_data = mesoscope_frame_data.with_columns(
        [
            # Creates pulse ID by counting rising edges.
            (pl.col("ttl_state").diff() == 1).fill_null(value=False).cum_sum().alias("pulse_id"),
            # Marks if this row is a rising edge.
            (pl.col("ttl_state").diff() == 1).fill_null(value=False).alias("is_rising_edge"),
            # Marks if this row is a falling edge.
            (pl.col("ttl_state").diff() == -1).fill_null(value=False).alias("is_falling_edge"),
        ]
    )

    # For each pulse, finds the rising and falling-edge times using window functions
    mesoscope_frame_data = mesoscope_frame_data.with_columns(
        [
            # Gets the time of the rising edge for this pulse
            pl.when(pl.col("is_rising_edge"))
            .then(pl.col("time_us"))
            .forward_fill()
            .over("pulse_id")
            .alias("pulse_start"),
            # Gets the time of the falling edge for this pulse
            pl.when(pl.col("is_falling_edge"))
            .then(pl.col("time_us"))
            .backward_fill()
            .over("pulse_id")
            .alias("pulse_end"),
        ]
    )

    # Calculates pulse duration for each recorded scan pulse
    mesoscope_frame_data = mesoscope_frame_data.with_columns(
        [((pl.col("pulse_end") - pl.col("pulse_start")) / 1000).alias("duration_ms")]
    )

    # Filters for valid duration pulses and gets unique frames
    frame_aligned_data: pl.DataFrame = (
        mesoscope_frame_data.filter(
            (pl.col("duration_ms") >= min_duration)
            & (pl.col("duration_ms") <= max_duration)
            & pl.col("duration_ms").is_not_null()
        )
        .group_by("pulse_id")
        .first()
        .select(
            [
                pl.col("pulse_id").alias("frame"),
                pl.col("pulse_start").alias("time_us"),
            ]
        )
        .sort("frame")
    )

    # If there are more frame pulses than expected based on the processed fluorescence data, keeps only the last
    # expected_frames number of datapoints
    original_frame_count = len(frame_aligned_data)
    if original_frame_count > frames:
        frame_aligned_data = frame_aligned_data.tail(frames)  # Keeps the last 'frames' number of pulses

    # Re-assigns frame IDs starting from 1 as unsigned 32-bit integers and adds a column that reflects the
    # within-session time as the number of minutes elapsed since session onset.
    frame_aligned_data = frame_aligned_data.with_columns(
        [
            pl.int_range(1, len(frame_aligned_data) + 1, dtype=pl.UInt32).alias("frame"),
            ((pl.col("time_us") - pl.col("time_us").min()) / (60 * 1_000_000)).round(2).alias("elapsed_minutes"),
        ]
    )

    # Uses the single-recording cell classification data to create a filtering mask that excludes non-cell ROIs from
    # the analysis dataset. cindra stores classification results as a (num_rois, 2) float32 array where column 0 holds
    # the is_cell label (1.0 or 0.0) and column 1 holds the classifier probability.
    classification = np.load(single_day_data.joinpath("cell_classification.npy"), mmap_mode="r")
    is_cell_mask: NDArray[np.bool_] = classification[:, 0] == 1

    # Adds single-recording fluorescence traces to each frame, filtering non-cell ROIs via the classification mask.
    single_day_files = [
        ("cell_fluorescence.npy", "single_day_cell_fluorescence"),
        ("neuropil_fluorescence.npy", "single_day_neuropil_fluorescence"),
        ("subtracted_fluorescence.npy", "single_day_subtracted_fluorescence"),
        ("spikes.npy", "single_day_spikes"),
    ]
    for filename, column_name in single_day_files:
        frame_aligned_data = _add_cindra_fluorescence_column(
            frame_aligned_data, single_day_data, filename, column_name, cell_mask=is_cell_mask
        )

    # Adds multi-recording fluorescence traces to each frame. Multi-recording traces already correspond to tracked
    # ROIs, so no cell mask is applied.
    multi_day_files = [
        ("cell_fluorescence.npy", "multi_day_cell_fluorescence"),
        ("neuropil_fluorescence.npy", "multi_day_neuropil_fluorescence"),
        ("subtracted_fluorescence.npy", "multi_day_subtracted_fluorescence"),
        ("spikes.npy", "multi_day_spikes"),
    ]
    for filename, column_name in multi_day_files:
        frame_aligned_data = _add_cindra_fluorescence_column(
            frame_aligned_data, multiday_data_path, filename, column_name, cell_mask=None
        )

    # Formats the elapsed minutes column to use fp32 precision and rounds to 2 decimal places.
    return frame_aligned_data.with_columns(pl.col("elapsed_minutes").cast(pl.Float32))
