"""Provides assets for assembling two-photon fluorescence datasets from cindra single-recording and multi-recording
processing pipeline outputs.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import polars as pl

if TYPE_CHECKING:
    from pathlib import Path

    from numpy.typing import NDArray


_MILLISECONDS_PER_SECOND: int = 1000
"""The number of milliseconds in one second."""

_MICROSECONDS_PER_MILLISECOND: int = 1000
"""The number of microseconds in one millisecond."""

_MICROSECONDS_PER_MINUTE: int = 60 * 1_000_000
"""The number of microseconds in one minute."""

_SCAN_PULSE_TOLERANCE_MS: int = 20
"""The tolerance, in milliseconds, applied around the expected scan pulse duration when filtering logged pulses."""


def assemble_cindra_dataset(cindra_data_path: Path, behavior_data_path: Path, multiday_data_path: Path) -> pl.DataFrame:
    """Assembles the target session's two-photon fluorescence dataset from the data generated by Cindra's
    single-recording and multi-recording processing pipelines.

    Args:
        cindra_data_path: The path to the single-recording cindra output directory containing the combined
            (multi-plane merged) fluorescence traces, cell classification, and metadata files.
        behavior_data_path: The path to the behavior data directory containing the mesoscope frame TTL timestamps.
        multiday_data_path: The path to the session's multi-recording cindra output directory (the directory that
            directly contains ``cell_fluorescence.npy`` and its companions).

    Returns:
        The Polars DataFrame that contains the assembled single-recording and multi-recording cell fluorescence data.
    """
    # Queries the number of frames processed by cindra via a memory-mapped header read. This handles rare cases where
    # the log has more frame stamps than recorded frames (typically when the user manually triggers mesoscope scanning
    # outside the expected time slot): if the log has more frames than the cindra data, the log is clipped at the
    # front, since aberrant frames must come from a period before the main experiment runtime.
    _, frames = np.load(file=cindra_data_path.joinpath("cell_fluorescence.npy"), mmap_mode="r").shape

    # Loads the combined cindra metadata archive and extracts the per-plane sampling rate in Hz. NPZ archives do not
    # support memory mapping, so the context manager is used to keep the archive open only long enough to pull the
    # scalar out. The scanning rate is used to derive the expected scan pulse duration window in milliseconds for
    # filtering logged scan pulses.
    with np.load(file=cindra_data_path.joinpath("combined_metadata.npz")) as metadata:
        scanning_frequency = float(metadata["sampling_rate"][0])
    expected_duration_ms = _MILLISECONDS_PER_SECOND / scanning_frequency
    min_duration = expected_duration_ms - _SCAN_PULSE_TOLERANCE_MS
    max_duration = expected_duration_ms + _SCAN_PULSE_TOLERANCE_MS

    # Loads the mesoscope frame acquisition timestamps collected by the microcontroller logging system during the
    # session's data acquisition.
    mesoscope_frame_data = pl.read_ipc(
        source=behavior_data_path.joinpath("mesoscope_frame_data.feather"), memory_map=True
    )

    # Sorts by time to ensure the correct order and computes TTL state transitions once.
    mesoscope_frame_data = mesoscope_frame_data.sort("time_us")
    ttl_diff = pl.col("ttl_state").diff().fill_null(value=0)
    mesoscope_frame_data = mesoscope_frame_data.with_columns(
        ttl_diff.alias("ttl_diff"),
        (ttl_diff == 1).cum_sum().alias("pulse_id"),
    )

    # Extracts one row per pulse via separate rising-edge (pulse start) and falling-edge (pulse end) filters, then
    # joins by pulse ID. This avoids intermediate boolean columns and per-row window evaluation (forward_fill /
    # backward_fill over groups). Pulses missing either edge are excluded by the inner join, matching the prior
    # is_not_null filter on pulse duration.
    rising_edges = mesoscope_frame_data.filter(pl.col("ttl_diff") == 1).select(
        "pulse_id", pl.col("time_us").alias("pulse_start")
    )
    falling_edges = mesoscope_frame_data.filter(pl.col("ttl_diff") == -1).select(
        "pulse_id", pl.col("time_us").alias("pulse_end")
    )

    frame_aligned_data: pl.DataFrame = (
        rising_edges.join(falling_edges, on="pulse_id", how="inner")
        .with_columns(
            ((pl.col("pulse_end") - pl.col("pulse_start")) / _MICROSECONDS_PER_MILLISECOND).alias("duration_ms")
        )
        .filter(pl.col("duration_ms").is_between(min_duration, max_duration))
        .select(
            pl.col("pulse_id").alias("frame"),
            pl.col("pulse_start").alias("time_us"),
        )
        .sort("frame")
    )

    # If there are more frame pulses than expected based on the processed fluorescence data, keeps only the last
    # expected_frames number of datapoints.
    if len(frame_aligned_data) > frames:
        frame_aligned_data = frame_aligned_data.tail(frames)

    # Re-assigns frame IDs starting from 1 as unsigned 32-bit integers and adds a column that reflects the
    # within-session time as the number of minutes elapsed since session onset (stored as fp32).
    frame_aligned_data = frame_aligned_data.with_columns(
        pl.int_range(1, len(frame_aligned_data) + 1, dtype=pl.UInt32).alias("frame"),
        ((pl.col("time_us") - pl.col("time_us").min()) / _MICROSECONDS_PER_MINUTE)
        .round(2)
        .cast(pl.Float32)
        .alias("elapsed_minutes"),
    )

    # Uses the single-recording cell classification data to create a filtering mask that excludes non-cell ROIs from
    # the analysis dataset. cindra stores classification results as a (num_rois, 2) float32 array where column 0 holds
    # the is_cell label (1.0 or 0.0) and column 1 holds the classifier probability.
    classification = np.load(file=cindra_data_path.joinpath("cell_classification.npy"), mmap_mode="r")
    is_cell_mask: NDArray[np.bool_] = classification[:, 0] == 1

    # Builds all fluorescence Series up front: single-day traces filtered by the cell classification mask, and
    # multi-day traces without filtering (already tracked ROIs). Adding all columns in a single with_columns call
    # avoids creating intermediate DataFrame copies for each file.
    fluorescence_columns = [
        _load_cindra_fluorescence(
            data_path=cindra_data_path, filename=filename, column_name=column_name, cell_mask=is_cell_mask
        )
        for filename, column_name in (
            ("cell_fluorescence.npy", "single_day_cell_fluorescence"),
            ("neuropil_fluorescence.npy", "single_day_neuropil_fluorescence"),
            ("subtracted_fluorescence.npy", "single_day_subtracted_fluorescence"),
            ("spikes.npy", "single_day_spikes"),
        )
    ] + [
        _load_cindra_fluorescence(data_path=multiday_data_path, filename=filename, column_name=column_name)
        for filename, column_name in (
            ("cell_fluorescence.npy", "multi_day_cell_fluorescence"),
            ("neuropil_fluorescence.npy", "multi_day_neuropil_fluorescence"),
            ("subtracted_fluorescence.npy", "multi_day_subtracted_fluorescence"),
            ("spikes.npy", "multi_day_spikes"),
        )
    ]

    return frame_aligned_data.with_columns(fluorescence_columns)


def _load_cindra_fluorescence(
    data_path: Path,
    filename: str,
    column_name: str,
    *,
    cell_mask: NDArray[np.bool_] | None = None,
) -> pl.Series:
    """Loads fluorescence data from a cindra .npy file and returns it as a Polars Array-typed Series.

    Args:
        data_path: The path to the directory that stores the fluorescence data to be loaded.
        filename: The name of the .npy file that stores the data to be loaded.
        column_name: The name to assign to the returned Series.
        cell_mask: The optional boolean mask to filter out non-cell ROIs. Must match the ROI axis of the loaded
            fluorescence array.

    Returns:
        A Polars Array-typed Series containing the fluorescence data with shape (frames, rois).
    """
    # Memory-maps the cindra fluorescence array to defer reading the pixel data until the selection is applied.
    fluorescence = np.load(file=data_path.joinpath(filename), mmap_mode="r")

    # Applies the cell mask if provided.
    if cell_mask is not None:
        fluorescence = fluorescence[cell_mask, :]

    # Transposes (ROI, Frame) to (Frame, ROI) as a contiguous float32 array. Polars constructs an Array-typed column
    # directly from the 2D numpy array, avoiding intermediate per-row Python list conversion.
    transposed = np.ascontiguousarray(fluorescence.T, dtype=np.float32)

    return pl.Series(name=column_name, values=transposed)
