# Data folder locations.
data:
  suite2p_folder: suite2p
  multiday_output_folder: multiday  # output folder for multiday data.
  save_folder: Results  # output folder for single day data.

# Animal Info.
animal:
  date_of_birth: "01-01-2020"
  gender: male
