from typing import Any
from pathlib import Path
from dataclasses import field, dataclass

from ataraxis_data_structures import YamlConfig

from .graph import BatchDocument as BatchDocument
from ..server import remote_state_path as remote_state_path

_BATCH_DIRECTORY_NAME: str
_LOCK_TIMEOUT_SECONDS: float
OUTCOME_FILE_SUFFIX: str

@dataclass
class _PreparedBatch(YamlConfig):
    batch_id: str = ...
    pipeline: str = ...
    host: str = ...
    document: dict[str, Any] = field(default_factory=dict)
    def as_document(self) -> BatchDocument: ...

@dataclass
class _RecordedOutcome(YamlConfig):
    outcome: dict[str, Any] = field(default_factory=dict)

def batch_directory() -> Path: ...
def record_prepared_batch(document: BatchDocument) -> str: ...
def read_prepared_batch(batch_id: str) -> BatchDocument | None: ...
def read_prepared_batches(batch_ids: list[str]) -> tuple[list[BatchDocument], list[str]]: ...
def resolve_batch_host(documents: list[BatchDocument]) -> str: ...
def forget_batch_records(batch_ids: list[str]) -> list[str]: ...
def record_batch_outcome(batch_id: str, outcome: dict[str, Any]) -> bool: ...
def read_batch_outcome(batch_id: str) -> dict[str, Any] | None: ...
def retire_prepared_batch(batch_id: str) -> None: ...
def _batch_path(batch_id: str) -> Path: ...
def _outcome_path(batch_id: str) -> Path: ...
def _lock_path(path: Path) -> Path: ...
def _remove_record(path: Path) -> bool: ...
