from typing import Any
from pathlib import Path
from dataclasses import field, dataclass
from collections.abc import Sequence

SUCCEEDED_STATUS: str

@dataclass(slots=True)
class PendingJob:
    tracker_path: Path
    job_id: str
    unit_path: Path = field(default_factory=Path)
    job_name: str = ...
    core_weight: int = ...
    memory_mb: int = ...
    prerequisite_ids: tuple[str, ...] = ...
    @property
    def dispatch_key(self) -> tuple[str, str]: ...
    @property
    def prerequisite_keys(self) -> tuple[tuple[str, str], ...]: ...

@dataclass(slots=True)
class GenericPendingJob(PendingJob):
    pipeline: str = ...
    name: str = ...
    specifier: str = ...
    project_root: Path | None = ...
    options: dict[str, Any] = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class BatchDocument:
    pipeline: str = ...
    host: str = ...
    options: dict[str, Any] = field(default_factory=dict)
    units: list[dict[str, Any]] = field(default_factory=list)
    jobs: list[dict[str, Any]] = field(default_factory=list)
    blocked_jobs: list[dict[str, Any]] = field(default_factory=list)

def build_batch_document(
    pipeline: str,
    host: str,
    unit_column: str,
    plan_rows: list[dict[str, Any]],
    state_rows: list[dict[str, Any]],
    unit_paths: Sequence[Path],
    options: dict[str, Any],
    tracker_paths: dict[str, str] | None = None,
) -> BatchDocument: ...
def build_job_descriptor(
    state_row: dict[str, Any],
    plan_row: dict[str, Any],
    unit_path: Path,
    unit_name: str,
    pipeline: str,
    options: dict[str, Any],
    trackable_ids: set[str],
    tracker_path: str = "",
) -> dict[str, Any]: ...
def index_rows_by_unit(rows: list[dict[str, Any]], key: str) -> dict[str, dict[str, dict[str, Any]]]: ...
def partition_blocked_jobs(
    jobs: list[dict[str, Any]], succeeded: set[str]
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]: ...
def resolve_dispatch_priorities[PendingJobT: PendingJob](
    jobs: dict[tuple[str, str], PendingJobT],
) -> dict[tuple[str, str], int]: ...
def resolve_submission_order[PendingJobT: PendingJob](jobs: Sequence[PendingJobT]) -> list[PendingJobT]: ...
def build_pending_job(job: dict[str, Any]) -> GenericPendingJob: ...
def _unresolved_unit(unit_path: Path, reason: str) -> dict[str, Any]: ...
def _no_state_reason(pipeline: str) -> str: ...
def _unplanned_reason(job_ids: list[str]) -> str: ...
