from typing import Any, NoReturn, Protocol
from pathlib import Path
from collections.abc import Mapping, Sequence

from ..server import Server as Server
from ..forging import (
    DATASET_STATE_FILENAME as DATASET_STATE_FILENAME,
    define_forging_dataset as define_forging_dataset,
    generate_dataset_state as generate_dataset_state,
    discover_project_datasets as discover_project_datasets,
)
from .dispatch import resolve_dispatch as resolve_dispatch
from .planning import (
    DATASET_UNIT as DATASET_UNIT,
    project_plan_path as project_plan_path,
    resolve_dataset_plan as resolve_dataset_plan,
    resolve_session_plan as resolve_session_plan,
    generate_project_plan as generate_project_plan,
)
from ..managing import (
    project_jobs_path as project_jobs_path,
    generate_project_manifest as generate_project_manifest,
)
from .maintenance import (
    reset_tracked_jobs as reset_tracked_jobs,
    clean_pipeline_output as clean_pipeline_output,
)

class ExecutionHost(Protocol):
    @property
    def label(self) -> str: ...
    def materialize(self, project_root: Path, unit_paths: Sequence[Path], unit_kind: str, *, replan: bool) -> None: ...
    def plan(
        self, project_root: Path, unit_paths: Sequence[Path], unit_kind: str, *, replan: bool
    ) -> list[dict[str, Any]]: ...
    def generate_state(self, project_root: Path, unit_paths: Sequence[Path], unit_kind: str) -> None: ...
    def read_rows(self, path: Path) -> list[dict[str, Any]]: ...
    def fetch(self, path: Path, destination: Path) -> Path | None: ...
    def reset_jobs(self, pipeline: str, job_ids_by_unit: Mapping[Path, Sequence[str]]) -> None: ...
    def clean(self, pipeline: str, unit_paths: Sequence[Path]) -> list[dict[str, Any]]: ...
    def define_dataset(
        self,
        project_root: Path,
        dataset_name: str,
        session_names: Sequence[str],
        recreate_animals: Sequence[str],
        *,
        force_recreate: bool,
    ) -> None: ...
    def resolve_tracker_paths(self, pipeline: str, unit_paths: Sequence[Path]) -> dict[str, str]: ...

class LocalHost:
    def __repr__(self) -> str: ...
    @property
    def label(self) -> str: ...
    @classmethod
    def materialize(cls, project_root: Path, unit_paths: Sequence[Path], unit_kind: str, *, replan: bool) -> None: ...
    @staticmethod
    def plan(
        project_root: Path, unit_paths: Sequence[Path], unit_kind: str, *, replan: bool
    ) -> list[dict[str, Any]]: ...
    @staticmethod
    def generate_state(project_root: Path, unit_paths: Sequence[Path], unit_kind: str) -> None: ...
    @staticmethod
    def read_rows(path: Path) -> list[dict[str, Any]]: ...
    @staticmethod
    def fetch(path: Path, destination: Path) -> Path | None: ...
    @staticmethod
    def reset_jobs(pipeline: str, job_ids_by_unit: Mapping[Path, Sequence[str]]) -> None: ...
    @staticmethod
    def clean(pipeline: str, unit_paths: Sequence[Path]) -> list[dict[str, Any]]: ...
    @staticmethod
    def define_dataset(
        project_root: Path,
        dataset_name: str,
        session_names: Sequence[str],
        recreate_animals: Sequence[str],
        *,
        force_recreate: bool,
    ) -> None: ...
    @staticmethod
    def resolve_tracker_paths(pipeline: str, unit_paths: Sequence[Path]) -> dict[str, str]: ...

class RemoteHost:
    _server: Server
    def __init__(self, server: Server) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def server(self) -> Server: ...
    def materialize(self, project_root: Path, unit_paths: Sequence[Path], unit_kind: str, *, replan: bool) -> None: ...
    def plan(
        self, project_root: Path, unit_paths: Sequence[Path], unit_kind: str, *, replan: bool
    ) -> list[dict[str, Any]]: ...
    def generate_state(self, project_root: Path, unit_paths: Sequence[Path], unit_kind: str) -> None: ...
    def read_rows(self, path: Path) -> list[dict[str, Any]]: ...
    def fetch(self, path: Path, destination: Path) -> Path | None: ...
    def reset_jobs(self, pipeline: str, job_ids_by_unit: Mapping[Path, Sequence[str]]) -> None: ...
    def clean(self, pipeline: str, unit_paths: Sequence[Path]) -> list[dict[str, Any]]: ...
    def define_dataset(
        self,
        project_root: Path,
        dataset_name: str,
        session_names: Sequence[str],
        recreate_animals: Sequence[str],
        *,
        force_recreate: bool,
    ) -> None: ...
    @staticmethod
    def resolve_tracker_paths(pipeline: str, unit_paths: Sequence[Path]) -> dict[str, str]: ...
    def _capture(self, commands: Sequence[Sequence[str]]) -> str: ...
    def _run(self, commands: Sequence[Sequence[str]]) -> None: ...

def _environment_commands(environment: str, commands: Sequence[Sequence[str]]) -> str: ...
def environment_command(environment: str, command: Sequence[str]) -> str: ...
def state_artifact_paths(project_root: Path, unit_paths: Sequence[Path], unit_kind: str) -> list[Path]: ...
def plan_artifact_path(project_root: Path) -> Path: ...
def _plan_commands(
    project_root: Path, unit_paths: Sequence[Path], unit_kind: str, *, replan: bool
) -> list[list[str]]: ...
def _summarize_planned_units(
    rows: list[dict[str, Any]], unit_paths: Sequence[Path], unit_kind: str
) -> list[dict[str, Any]]: ...
def _state_command(project_root: Path, unit_paths: Sequence[Path], unit_kind: str) -> list[str]: ...
def _parse_removals(output: str) -> list[dict[str, Any]]: ...
def _definition_command(
    project_root: Path,
    dataset_name: str,
    session_names: Sequence[str],
    recreate_animals: Sequence[str],
    *,
    force_recreate: bool,
) -> list[str]: ...
def _raise_command_failure(commands: Sequence[Sequence[str]], return_code: int, stderr: str) -> NoReturn: ...
def _repeated(flag: str, values: Sequence[Path]) -> list[str]: ...
