from pathlib import Path
from dataclasses import field, dataclass
from collections.abc import Sequence

from filelock import FileLock
from ataraxis_data_structures import YamlConfig

from ..server import remote_state_path as remote_state_path

_LEDGER_FILENAME: str
_LOCK_TIMEOUT_SECONDS: float

@dataclass(frozen=True, slots=True)
class RemoteSubmission:
    job_id: str = ...
    slurm_job_id: str = ...
    slurm_job_name: str = ...
    pipeline: str = ...
    job_name: str = ...
    specifier: str = ...
    unit_path: str = ...
    unit_name: str = ...
    cores: int = ...
    resident_mb: int = ...
    output_log: str = ...
    error_log: str = ...

@dataclass(frozen=True, slots=True)
class SubmissionBatch:
    batch_id: str = ...
    batch_ids: list[str] = field(default_factory=list)
    batch_directory: str = ...
    submitted_at: int = ...
    walltime_minutes: int = ...
    submissions: list[RemoteSubmission] = field(default_factory=list)
    @property
    def pipelines(self) -> list[str]: ...
    @property
    def covered_batch_ids(self) -> list[str]: ...

@dataclass
class SubmissionLedger(YamlConfig):
    batches: list[SubmissionBatch] = field(default_factory=list)
    def resolve_batch(self, batch_id: str) -> SubmissionBatch | None: ...

def read_ledger() -> SubmissionLedger: ...
def record_batch(batch: SubmissionBatch, resubmitted: Sequence[tuple[str, str]] | None = None) -> SubmissionLedger: ...
def forget_batches(batch_ids: Sequence[str]) -> list[str]: ...
def resolve_batches(ledger: SubmissionLedger, batch_ids: Sequence[str] | None = None) -> list[SubmissionBatch]: ...
def current_timestamp() -> int: ...
def _ledger_path() -> Path: ...
def _save_ledger(ledger: SubmissionLedger) -> None: ...
def _ledger_lock() -> FileLock: ...
