from typing import Any
from dataclasses import dataclass
from collections.abc import Iterable, Sequence

import polars as pl
from ataraxis_time import PrecisionTimer as PrecisionTimer

_DEFAULT_ITEM_LIMIT: int
_DEFAULT_DETAILED_LIMIT: int
_BREAKDOWN_AXIS_LIMIT: int

@dataclass(frozen=True, slots=True)
class _PageWindow:
    start: int
    length: int | None
    next_start_row: int | None
    @property
    def stop(self) -> int | None: ...

def resolve_page(total: int, limit: int, start_row: int) -> _PageWindow: ...
def page_fields(window: _PageWindow, total: int, listed: int) -> dict[str, Any]: ...
def count_values(values: Iterable[Any]) -> dict[str, int]: ...
def bounded_counts(values: Iterable[Any]) -> dict[str, Any]: ...
def frame_breakdown(frame: pl.DataFrame, axes: tuple[str, ...]) -> dict[str, dict[str, Any]]: ...
def resolve_elapsed_seconds(timer: PrecisionTimer) -> float: ...
def resolve_detail_limit(limit: int | None, *, detailed: bool) -> int: ...
def project_item(item: dict[str, Any], fields: Sequence[str], *, drop_empty: bool = True) -> dict[str, Any]: ...
def ok_response(**payload: Any) -> dict[str, Any]: ...
def error_response(message: str) -> dict[str, Any]: ...
def reject_unknown(frame: pl.DataFrame, column: str, values: list[str], subject: str) -> dict[str, Any] | None: ...
