from typing import Any
from pathlib import Path

from ..server import (
    Server as Server,
    discover_project_data as discover_project_data,
    get_server_configuration as get_server_configuration,
    create_server_configuration_file as create_server_configuration_file,
)
from .remote_tools import (
    remote_batch_retire as remote_batch_retire,
    remote_batch_status as remote_batch_status,
)
from ..orchestration import STALLED_BATCH as STALLED_BATCH

_CONTEXT_SETTINGS: dict[str, int]
_SACCT_FORMAT: str
_SACCT_HEADERS: list[str]
_SQUEUE_FORMAT: str
_SQUEUE_MISSING_JOB_ERROR: str
_BATCH_HEADERS: list[str]
_ALLOCATION_HEADERS: list[str]
_REMEDIATION_HEADERS: list[str]
_MINIMUM_SACCT_ROWS: int
_SACCT_COLUMN_COUNT: int

def server_cli() -> None: ...
def configure_server(username: str, password: str, host: str, root: str, environment: str) -> None: ...
def print_slurm_info(
    *, job_data: bool, queue: bool, user: str | None, job_id: str | None, start_time: str | None, end_time: str | None
) -> None: ...
def discover_project_sessions_command(project: str) -> None: ...
def report_remote_batches_command(batch_id: tuple[str, ...], *, allocations: bool) -> None: ...
def retire_remote_batch_command(batch_id: tuple[str, ...], *, force: bool, drop_without_outcome: bool) -> None: ...
def _report_allocations(jobs: list[dict[str, Any]]) -> None: ...
def _reject_failed_response(response: dict[str, Any]) -> None: ...
def _format_outstanding(seconds: float | None) -> str: ...
def _report_job_accounting(
    server: Server, user: str, job_id: str | None, start_time: str | None, end_time: str | None, *, all_users: bool
) -> None: ...
def _report_queue_status(server: Server, user: str, job_id: str | None, *, all_users: bool) -> None: ...
def _format_slurm_output(raw_output: str) -> str: ...
def _format_sacct_output(raw_output: str) -> str: ...
def pull_command(remote_path: str, destination: Path) -> None: ...
