from ..server import (
    Server as Server,
    discover_project_data as discover_project_data,
    get_server_configuration as get_server_configuration,
    create_server_configuration_file as create_server_configuration_file,
)

_CONTEXT_SETTINGS: dict[str, int]
_SACCT_FORMAT: str
_SACCT_HEADERS: list[str]
_SQUEUE_FORMAT: str
_MINIMUM_SACCT_ROWS: int
_SACCT_COLUMN_COUNT: int

def server_cli() -> None: ...
def configure_server(username: str, password: str, host: str, root: str, environment: str) -> None: ...
def print_slurm_info(
    *, job_data: bool, queue: bool, user: str | None, job_id: str | None, start_time: str | None, end_time: str | None
) -> None: ...
def discover_project_sessions_command(project: str) -> None: ...
def _report_job_accounting(
    server: Server, user: str, job_id: str | None, start_time: str | None, end_time: str | None, *, all_users: bool
) -> None: ...
def _report_queue_status(server: Server, user: str, *, all_users: bool) -> None: ...
def _format_slurm_output(raw_output: str) -> str: ...
def _format_sacct_output(raw_output: str) -> str: ...
