from pathlib import Path
from dataclasses import dataclass

from ataraxis_data_structures import YamlConfig

_SERVER_CONFIGURATION_FILENAME: str
_CONFIGURATION_DIRECTORY: str
_REMOTE_STATE_DIRECTORY: str

@dataclass
class ServerConfiguration(YamlConfig):
    username: str = ...
    password: str = ...
    host: str = ...
    root: str = ...
    environment: str = ...

def create_server_configuration_file(username: str, password: str, host: str, root: str, environment: str) -> None: ...
def get_server_configuration() -> ServerConfiguration: ...
def get_server_configuration_path() -> Path: ...
def remote_state_path() -> Path: ...
def remote_state_directory(project: str) -> Path: ...
