from enum import StrEnum
from types import TracebackType
from typing import Self
from pathlib import Path
from dataclasses import dataclass
from collections.abc import Sequence

from paramiko.client import SSHClient
from paramiko.sftp_client import SFTPClient

from .job import Job as Job
from .server_configuration import ServerConfiguration as ServerConfiguration

_BLOCKED_QUEUE_REASON: str
_MAXIMUM_CONNECTION_RETRIES: int
_EXPECTED_FIELD_COUNT: int

@dataclass(frozen=True, slots=True)
class CommandResult:
    stdout: str
    stderr: str
    return_code: int

class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"
    NODE_FAIL = "NODE_FAIL"
    OUT_OF_MEMORY = "OUT_OF_MEMORY"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

TERMINAL_JOB_STATUSES: frozenset[JobStatus]

class Server:
    _open: bool
    _configuration: ServerConfiguration
    _client: SSHClient
    _sftp: SFTPClient
    def __init__(self, configuration: ServerConfiguration) -> None: ...
    def __del__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def submit_job(self, job: Job, *, verbose: bool = True) -> Job: ...
    def abort_job(self, slurm_job_id: str) -> None: ...
    def abort_jobs(self, slurm_job_ids: Sequence[str]) -> None: ...
    def get_job_status(self, slurm_job_id: str) -> JobStatus: ...
    def get_job_statuses(self, slurm_job_ids: Sequence[str]) -> dict[str, JobStatus]: ...
    def get_blocked_job_ids(self) -> set[str]: ...
    def pull(self, local_path: Path, remote_path: Path) -> None: ...
    def _pull_directory(self, local_path: Path, remote_path: Path) -> None: ...
    def push(self, local_path: Path, remote_path: Path) -> None: ...
    def _push_directory(self, local_path: Path, remote_path: Path) -> None: ...
    def create(self, remote_path: Path, *, is_dir: bool = True, parents: bool = True) -> None: ...
    def _create_directory(self, remote_path: Path, *, parents: bool = True) -> None: ...
    def remove(self, remote_path: Path, *, is_dir: bool, recursive: bool = False) -> None: ...
    def _recursive_remove(self, remote_path: Path) -> None: ...
    def exists(self, remote_path: Path) -> bool: ...
    def is_directory(self, remote_path: Path) -> bool: ...
    def list_directory(self, remote_path: Path) -> list[str]: ...
    def execute_command(self, command: str) -> CommandResult: ...
    def close(self) -> None: ...
    @property
    def root(self) -> Path: ...
    @property
    def host(self) -> str: ...
    @property
    def user(self) -> str: ...
    @property
    def environment(self) -> str: ...
    @property
    def cindra_configurations_directory(self) -> Path: ...
    @property
    def dlc_projects_directory(self) -> Path: ...

def _parse_job_status(state: str) -> JobStatus: ...
