"""Provides assets for discovering, reading, and extracting acquisition-system and runtime task data from .npz log
archives generated by the Mesoscope-VR data acquisition system used in the Sollertia platform.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from numba import njit  # type: ignore[import-untyped]
import numpy as np
import polars as pl
from numpy.typing import NDArray  # noqa: TC002 - Required at runtime for Numba type introspection
from ataraxis_base_utilities import console
from ataraxis_data_structures import LogArchiveReader

if TYPE_CHECKING:
    from pathlib import Path

    from sollertia_shared_assets import GasPuffTrial, WaterRewardTrial, MesoscopeExperimentConfiguration

RUNTIME_SOURCE_ID: str = "1"
"""The source ID used by the Mesoscope-VR runtime DataLogger for its log archive. Every processable session
contains exactly one runtime archive, and it always uses this ID."""

_LOG_ARCHIVE_NAME: str = f"{RUNTIME_SOURCE_ID}_log.npz"
"""The expected filename for the runtime log archive."""

_CUE_SEQUENCE_MIN_LENGTH: int = 500
"""The minimum length, in bytes, of a valid VR wall cue sequence message."""

_SYSTEM_STATE_CODE: int = 1
"""The message code for VR system state data."""

_RUNTIME_STATE_CODE: int = 2
"""The message code for session runtime state data."""

_REINFORCING_GUIDANCE_STATE_CODE: int = 3
"""The message code for reinforcing trial guidance state data."""

_AVERSIVE_GUIDANCE_STATE_CODE: int = 4
"""The message code for aversive trial guidance state data."""

_DISTANCE_SNAPSHOT_CODE: int = 5
"""The message code for distance snapshot data logged when VR wall cue sequence changes."""


def find_log_archive(data_directory: Path) -> Path | None:
    """Resolves the runtime log archive inside the canonical raw behavior data directory.

    Looks for the single ``{RUNTIME_SOURCE_ID}_log.npz`` archive produced by the Mesoscope-VR runtime
    DataLogger at the canonical location ``data_directory / {RUNTIME_SOURCE_ID}_log.npz``. The runtime
    DataLogger always writes to a fixed source ID, so at most one archive is expected per session.

    Args:
        data_directory: The path to the session's raw behavior data directory (``session.raw_behavior_data_path``).

    Returns:
        The path to the runtime log archive, or None if the directory does not exist or no archive is present.
    """
    if not data_directory.is_dir():
        return None

    archive_path = data_directory.joinpath(_LOG_ARCHIVE_NAME)
    if not archive_path.is_file():
        return None

    return archive_path


def process_runtime_data(
    log_path: Path,
    output_directory: Path,
    experiment_configuration: MesoscopeExperimentConfiguration | None = None,
) -> None:
    """Extracts acquisition system and runtime task data from a Mesoscope-VR .npz log archive.

    Notes:
        Uses LogArchiveReader from ataraxis-data-structures to read the archive with automatic onset timestamp
        resolution. The reader handles onset discovery and provides absolute UTC timestamps for each message,
        eliminating the need for manual timestamp offset calculations.

    Args:
        log_path: The path to the .npz archive containing the Mesoscope-VR acquisition system data to extract.
        output_directory: The path to the directory where to save the extracted data as uncompressed .feather files.
        experiment_configuration: The MesoscopeExperimentConfiguration instance for the processed session. Only
            required if the processed session is an experiment session.
    """
    # Creates a LogArchiveReader to efficiently iterate through the archive with automatic onset resolution.
    reader = LogArchiveReader(archive_path=log_path)

    # Pre-creates the variables used to store extracted data.
    system_states: list[np.uint8] = []
    system_timestamps: list[np.uint64] = []
    runtime_states: list[np.uint8] = []
    runtime_timestamps: list[np.uint64] = []
    reinforcing_guidance_states: list[np.uint8] = []
    reinforcing_guidance_timestamps: list[np.uint64] = []
    aversive_guidance_states: list[np.uint8] = []
    aversive_guidance_timestamps: list[np.uint64] = []
    cue_sequences: list[NDArray[np.uint8]] = []
    distance_snapshots: list[np.float64] = []

    # Iterates through all messages in the archive. LogArchiveReader handles onset discovery and provides absolute
    # UTC timestamps automatically.
    for message in reader.iter_messages():
        timestamp = message.timestamp_us
        payload = message.payload

        # Long payloads (> _CUE_SEQUENCE_MIN_LENGTH bytes) are VR wall cue sequences.
        if len(payload) > _CUE_SEQUENCE_MIN_LENGTH and experiment_configuration is not None:
            cue_sequences.append(payload.view(dtype=np.uint8).astype(np.uint8))

        elif payload[0] == _SYSTEM_STATE_CODE:
            system_states.append(np.uint8(payload[1]))
            system_timestamps.append(timestamp)

        elif payload[0] == _RUNTIME_STATE_CODE:
            runtime_states.append(np.uint8(payload[1]))
            runtime_timestamps.append(timestamp)

        elif payload[0] == _REINFORCING_GUIDANCE_STATE_CODE:
            reinforcing_guidance_states.append(np.uint8(payload[1]))
            reinforcing_guidance_timestamps.append(timestamp)

        elif payload[0] == _AVERSIVE_GUIDANCE_STATE_CODE:
            aversive_guidance_states.append(np.uint8(payload[1]))
            aversive_guidance_timestamps.append(timestamp)

        elif payload[0] == _DISTANCE_SNAPSHOT_CODE:
            distance_bytes = payload[1:9]
            traveled_distance = np.float64(distance_bytes.view(dtype="<f8")[0])
            distance_snapshots.append(traveled_distance)

    # Ensures the output directory exists.
    output_directory.mkdir(parents=True, exist_ok=True)

    # Exports system state data.
    system_dataframe = pl.DataFrame({"time_us": system_timestamps, "system_state": system_states})
    system_dataframe.write_ipc(file=output_directory / "system_state_data.feather", compression="uncompressed")

    # Exports runtime state data.
    runtime_dataframe = pl.DataFrame({"time_us": runtime_timestamps, "runtime_state": runtime_states})
    runtime_dataframe.write_ipc(file=output_directory / "runtime_state_data.feather", compression="uncompressed")

    # Exports experiment-specific data only for experiment sessions.
    if experiment_configuration is not None:
        # Exports reinforcing guidance state data if present.
        if reinforcing_guidance_states:
            reinforcing_dataframe = pl.DataFrame(
                {"time_us": reinforcing_guidance_timestamps, "reinforcing_guidance_state": reinforcing_guidance_states}
            )
            reinforcing_dataframe.write_ipc(
                file=output_directory / "reinforcing_guidance_state_data.feather", compression="uncompressed"
            )

        # Exports aversive guidance state data if present.
        if aversive_guidance_states:
            aversive_dataframe = pl.DataFrame(
                {"time_us": aversive_guidance_timestamps, "aversive_guidance_state": aversive_guidance_states}
            )
            aversive_dataframe.write_ipc(
                file=output_directory / "aversive_guidance_state_data.feather", compression="uncompressed"
            )

        # Decomposes cue sequences into trials, handling single or multiple sequences.
        trial_types, trial_distances = _decompose_multiple_cue_sequences_into_trials(
            experiment_configuration=experiment_configuration,
            cue_sequences=cue_sequences,
            distance_breakpoints=distance_snapshots,
        )

        # Processes the trial sequence to extract cue, trigger zone, and trial start metadata.
        cue_sequence, distance_sequence, trigger_start, trigger_end, trial_start = _process_trial_sequence(
            experiment_configuration=experiment_configuration,
            trial_types=trial_types,
            trial_distances=trial_distances,
        )

        # Exports VR cue-distance mapping.
        cue_dataframe = pl.DataFrame({"vr_cue": cue_sequence, "traveled_distance_cm": distance_sequence})
        cue_dataframe.write_ipc(file=output_directory / "vr_cue_data.feather", compression="uncompressed")

        # Exports trigger zone boundaries.
        trigger_zone_dataframe = pl.DataFrame(
            {"trigger_zone_start_cm": trigger_start, "trigger_zone_end_cm": trigger_end}
        )
        trigger_zone_dataframe.write_ipc(
            file=output_directory / "vr_trigger_zone_data.feather", compression="uncompressed"
        )

        # Exports trial type and start distance data.
        trial_dataframe = pl.DataFrame({"trial_type_index": trial_types, "traveled_distance_cm": trial_start})
        trial_dataframe.write_ipc(file=output_directory / "trial_data.feather", compression="uncompressed")


def _decompose_multiple_cue_sequences_into_trials(
    experiment_configuration: MesoscopeExperimentConfiguration,
    cue_sequences: list[NDArray[np.uint8]],
    distance_breakpoints: list[np.float64],
) -> tuple[NDArray[np.int32], NDArray[np.float64]]:
    """Decomposes multiple Virtual Reality environment cue sequences into a unified sequence of trials.

    Notes:
        Handles cases where the original cue sequence was interrupted and a new sequence was generated during runtime.
        Uses distance breakpoints to stitch sequences together correctly.

    Args:
        experiment_configuration: The MesoscopeExperimentConfiguration instance for the processed session.
        cue_sequences: The Virtual Reality environment cue sequences in the order they were used during runtime.
        distance_breakpoints: The cumulative distances, in centimeters, at which each sequence ends. Should have
            the same number of elements as the number of cue sequences minus one.

    Returns:
        A tuple of two elements. The first element is an array of trial type indices stored in the order encountered
        during runtime. The second element is an array of cumulative distances at the end of each trial.

    Raises:
        ValueError: If the number of breakpoints does not match the number of sequences minus one, or if no cue
            sequences are provided.
        RuntimeError: If the function is unable to fully decompose any of the cue sequences.
    """
    if not cue_sequences:
        message = (
            "Unable to decompose input cue sequence(s) into trials. Expected at least one cue sequence as input, but "
            "received none."
        )
        console.error(message=message, error=ValueError)

    if len(cue_sequences) > 1 and len(distance_breakpoints) != len(cue_sequences) - 1:
        message = (
            f"Unable to decompose input cue sequence(s) into trials. Expected the number of distance breakpoints "
            f"to be {len(cue_sequences) - 1} (number of sequences - 1), but encountered {len(distance_breakpoints)}."
        )
        console.error(message=message, error=ValueError)

    # Extracts the list of trial structures supported by the processed experiment runtime.
    trials: list[WaterRewardTrial | GasPuffTrial] = list(experiment_configuration.trial_structures.values())

    # Extracts trial motifs and their corresponding distances in centimeters.
    # noinspection PyTypeChecker
    trial_motifs: list[NDArray[np.uint8]] = [np.asarray(trial.cue_sequence).astype(np.uint8) for trial in trials]
    trial_distances: list[float] = [float(trial.trial_length_cm) for trial in trials]

    # Prepares the flattened motif data for numba-accelerated decomposition.
    motifs_flat, motif_starts, motif_lengths, motif_indices, distances_array = _prepare_motif_data(
        trial_motifs=trial_motifs, trial_distances=trial_distances
    )

    # Estimates the maximum number of trials across all sequences.
    min_motif_length = min(len(motif) for motif in trial_motifs)
    total_cue_length = sum(len(sequence) for sequence in cue_sequences)
    max_trials = total_cue_length // min_motif_length + 1

    # Processes each sequence and collects results.
    all_trial_indices: list[int] = []
    all_trial_distances: list[float] = []
    cumulative_distance = 0.0

    for sequence_index, cue_sequence in enumerate(cue_sequences):
        # Decomposes the current sequence using numba-accelerated matching.
        trial_indices_array, trial_count = _decompose_sequence_numba_flat(
            cue_sequence=cue_sequence,
            motifs_flat=motifs_flat,
            motif_starts=motif_starts,
            motif_lengths=motif_lengths,
            motif_indices=motif_indices,
            max_trials=max_trials,
        )

        # Checks for decomposition errors.
        if trial_count == -1:
            sequence_position = 0
            trial_indices_list = trial_indices_array[:max_trials].tolist()

            for trial_index in trial_indices_list:
                if trial_index == 0 and sequence_position > 0:
                    break
                sequence_position += len(trial_motifs[trial_index])

            remaining_sequence = cue_sequence[sequence_position : sequence_position + 20]
            message = (
                f"Unable to decompose VR wall cue sequence {sequence_index + 1} of {len(cue_sequences)} into a "
                f"sequence of trial distances. No trial motif matched at position {sequence_position}. The next "
                f"20 cues: {remaining_sequence.tolist()}"
            )
            console.error(message=message, error=RuntimeError)

        # Processes decomposed trials and handles breakpoint-based truncation.
        sequence_trial_indices = trial_indices_array[:trial_count].tolist()

        for trial_index in sequence_trial_indices:
            trial_distance = distances_array[trial_index]
            new_cumulative_distance = cumulative_distance + trial_distance

            # Handles breakpoint-based truncation for non-final sequences.
            if sequence_index < len(cue_sequences) - 1:
                breakpoint_distance = distance_breakpoints[sequence_index]

                if new_cumulative_distance > breakpoint_distance:
                    truncated_distance = breakpoint_distance - cumulative_distance

                    if truncated_distance > 0:
                        all_trial_indices.append(trial_index)
                        all_trial_distances.append(float(breakpoint_distance))

                    cumulative_distance = breakpoint_distance
                    break

            all_trial_indices.append(trial_index)
            all_trial_distances.append(float(new_cumulative_distance))
            cumulative_distance = new_cumulative_distance

    trial_type_sequence: NDArray[np.int32] = np.array(all_trial_indices, dtype=np.int32).astype(np.int32)
    trial_distance_sequence: NDArray[np.float64] = np.array(all_trial_distances, dtype=np.float64).astype(np.float64)

    return trial_type_sequence, trial_distance_sequence


def _prepare_motif_data(
    trial_motifs: list[NDArray[np.uint8]], trial_distances: list[float]
) -> tuple[NDArray[np.uint8], NDArray[np.int32], NDArray[np.int32], NDArray[np.int32], NDArray[np.float32]]:
    """Prepares the flattened motif data for faster cue sequence-to-trial decomposition.

    Args:
        trial_motifs: The trial motifs (wall cue sequences) to decompose.
        trial_distances: The trial motif distances, in centimeters.

    Returns:
        A tuple with five elements. The first element is the flattened array that stores all motifs. The second
        element is the array that stores the starting indices of each motif in the flattened array. The third
        element is the array that stores the length of each motif, in cues. The fourth element is the array
        that stores the original indices of motifs before sorting. The fifth element is the array of trial distances
        in centimeters.
    """
    # Sorts motifs by length (longest first) for greedy matching optimization.
    motif_data: list[tuple[int, NDArray[np.uint8], int]] = [
        (i, motif, len(motif)) for i, motif in enumerate(trial_motifs)
    ]
    motif_data.sort(key=lambda x: x[2], reverse=True)

    # Calculates total size needed to represent all motifs in a single array.
    total_size: int = sum(len(motif) for motif in trial_motifs)
    motif_count: int = len(trial_motifs)

    # Creates arrays with specified dtypes.
    motifs_flat: NDArray[np.uint8] = np.zeros(total_size, dtype=np.uint8).astype(np.uint8)
    motif_starts: NDArray[np.int32] = np.zeros(motif_count, dtype=np.int32).astype(np.int32)
    motif_lengths: NDArray[np.int32] = np.zeros(motif_count, dtype=np.int32).astype(np.int32)
    motif_indices: NDArray[np.int32] = np.zeros(motif_count, dtype=np.int32).astype(np.int32)

    # Fills the arrays with sorted motif data.
    current_position: int = 0
    for i, (original_index, motif, length) in enumerate(motif_data):
        motif_uint8 = motif.astype(np.uint8) if motif.dtype != np.uint8 else motif
        motifs_flat[current_position : current_position + length] = motif_uint8
        motif_starts[i] = current_position
        motif_lengths[i] = length
        motif_indices[i] = original_index
        current_position += length

    distances_array: NDArray[np.float32] = np.array(trial_distances, dtype=np.float32).astype(np.float32)

    return motifs_flat, motif_starts, motif_lengths, motif_indices, distances_array


@njit(cache=True)
def _decompose_sequence_numba_flat(
    cue_sequence: NDArray[np.uint8],
    motifs_flat: NDArray[np.uint8],
    motif_starts: NDArray[np.int32],
    motif_lengths: NDArray[np.int32],
    motif_indices: NDArray[np.int32],
    max_trials: int,
) -> tuple[NDArray[np.int32], int]:
    """Decomposes a long sequence of Virtual Reality wall cues into individual trial motifs.

    Notes:
        Uses numba-acceleration to speed up decomposition. Longer motifs are matched preferentially over shorter
        ones to prevent partial matches.

    Args:
        cue_sequence: The full Virtual Reality environment cue sequence to decompose.
        motifs_flat: All trial type motifs concatenated into a single 1D array, sorted by length.
        motif_starts: The starting index of each unique motif in the motifs_flat array.
        motif_lengths: The length of each unique motif in the motifs_flat array.
        motif_indices: The original trial type motif indices before sorting.
        max_trials: The maximum number of trials that can make up the entire cue sequence.

    Returns:
        A tuple of two elements. The first element is the array of trial-type indices decoded from the cue
        sequence. The second element is the total number of trials extracted, or -1 if decomposition failed.
    """
    # noinspection PyTypeChecker
    trial_indices: NDArray[np.int32] = np.zeros(max_trials, dtype=np.int32)
    trial_count = 0
    sequence_position = 0
    sequence_length = len(cue_sequence)
    num_motifs = len(motif_lengths)

    # Decomposes the sequence into trial motifs using greedy matching.
    while sequence_position < sequence_length and trial_count < max_trials:
        motif_found = False

        for i in range(num_motifs):
            motif_length = motif_lengths[i]

            if sequence_position + motif_length <= sequence_length:
                motif_start = motif_starts[i]

                match = True
                for j in range(motif_length):
                    if cue_sequence[sequence_position + j] != motifs_flat[motif_start + j]:
                        match = False
                        break

                if match:
                    trial_indices[trial_count] = motif_indices[i]
                    trial_count += 1
                    sequence_position += motif_length
                    motif_found = True
                    break

        if not motif_found:
            return trial_indices, -1

    return trial_indices[:trial_count], trial_count


def _process_trial_sequence(
    experiment_configuration: MesoscopeExperimentConfiguration,
    trial_types: NDArray[np.int32],
    trial_distances: NDArray[np.float64],
) -> tuple[NDArray[np.uint8], NDArray[np.float64], NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]:
    """Processes the sequence of trials experienced by the animal during runtime to extract trial metadata.

    Notes:
        Processes the trial sequences generated by the cue decomposition functions. The metadata extracted supports
        trial-based data analysis in downstream processing.

    Args:
        experiment_configuration: The MesoscopeExperimentConfiguration instance for the processed session.
        trial_types: The indices used to query the trial data for each trial experienced by the animal during runtime.
        trial_distances: The cumulative traveled distance, in centimeters, at which the animal fully completed each
            trial during runtime. The elements in this array use the same order as elements in the trial_types array.

    Returns:
        A tuple of five NumPy arrays. The first array stores the IDs of the Virtual Reality environment cues
        experienced by the animal during runtime. The second array stores the cumulative distance, in centimeters,
        traveled by the animal at the onset of each cue. The third array stores the cumulative distance traveled by
        the animal when it entered each trial's trigger zone. The fourth array stores the cumulative distance
        traveled by the animal when it left each trial's trigger zone. The fifth array stores the cumulative
        distance traveled by the animal at the start of each trial.
    """
    # Extracts the list of trial type objects from experiment configuration data.
    trials: list[WaterRewardTrial | GasPuffTrial] = list(experiment_configuration.trial_structures.values())

    # Extracts the cue-to-length mapping and the starting position offset.
    cue_offset = experiment_configuration.cue_offset_cm
    cue_map = {cue.code: cue.length_cm for cue in experiment_configuration.cues}

    # Pre-initializes output lists.
    distances_list: list[np.float64] = []
    cues_list: list[np.uint8] = []
    trigger_zone_starts_list: list[np.float64] = []
    trigger_zone_ends_list: list[np.float64] = []
    trial_start_distances_list: list[np.float64] = []

    cumulative_distance = np.float64(0)
    apply_offset_to_next_cue = True
    previous_trial_end_distance = np.float64(0)

    index: int
    trial: np.int32
    for index, trial in enumerate(trial_types):
        trial_type = trials[trial]
        trial_start_distances_list.append(previous_trial_end_distance)

        actual_trial_distance = trial_distances[index] - previous_trial_end_distance
        trial_cue_sequence = trial_type.cue_sequence
        distance_within_trial = np.float64(0)

        for cue_index, cue_id in enumerate(trial_cue_sequence):
            cue_length = cue_map[int(cue_id)]

            # Applies the starting position offset for the first cue after a sequence start or restart.
            if apply_offset_to_next_cue and cue_index == 0:
                effective_distance_to_next_cue = cue_length - cue_offset
                apply_offset_to_next_cue = False
            else:
                effective_distance_to_next_cue = cue_length

            # Handles trial truncation when the trial was abruptly ended before completion.
            if distance_within_trial + effective_distance_to_next_cue > actual_trial_distance:
                cues_list.append(np.uint8(cue_id))
                distances_list.append(cumulative_distance)
                cumulative_distance = previous_trial_end_distance + actual_trial_distance
                apply_offset_to_next_cue = True
                break

            cues_list.append(np.uint8(cue_id))
            distances_list.append(cumulative_distance)
            cumulative_distance += effective_distance_to_next_cue
            distance_within_trial += effective_distance_to_next_cue

        # Computes absolute trigger zone boundaries from trial-relative positions.
        trigger_start_relative = trial_type.stimulus_trigger_zone_start_cm
        trigger_end_relative = trial_type.stimulus_trigger_zone_end_cm
        trigger_start_absolute = previous_trial_end_distance + trigger_start_relative
        trigger_end_absolute = previous_trial_end_distance + trigger_end_relative

        if trigger_start_absolute <= trial_distances[index]:
            # noinspection PyTypeChecker
            trigger_zone_starts_list.append(trigger_start_absolute)

            if trigger_end_absolute <= trial_distances[index]:
                # noinspection PyTypeChecker
                trigger_zone_ends_list.append(trigger_end_absolute)
            else:
                trigger_zone_ends_list.append(np.float64(trial_distances[index]))

        previous_trial_end_distance = trial_distances[index]

    distances: NDArray[np.float64] = np.array(distances_list, dtype=np.float64).astype(np.float64)
    cues: NDArray[np.uint8] = np.array(cues_list, dtype=np.uint8).astype(np.uint8)
    trigger_zone_starts: NDArray[np.float64] = np.array(trigger_zone_starts_list, dtype=np.float64).astype(np.float64)
    trigger_zone_ends: NDArray[np.float64] = np.array(trigger_zone_ends_list, dtype=np.float64).astype(np.float64)
    trial_start_distances: NDArray[np.float64] = np.array(trial_start_distances_list, dtype=np.float64).astype(
        np.float64
    )

    return cues, distances, trigger_zone_starts, trigger_zone_ends, trial_start_distances
